import json
import os

filepath = r'c:\Users\HP\Documents\projet touristique\dataset\lieux_touristiques.json'

with open(filepath, 'r', encoding='utf-8') as f:
    lieux = json.load(f)

# Ensure no duplicates in loading
ids = {l['id'] for l in lieux}

def add_lieu(id_val, nom, cat, scat, lat, lon, adr, qrt, d_fr, d_en, d_ar, note, avis, prix, gratuit, duree_min, duree_max, tags, saison, pmr, img, web, tel):
    if id_val in ids: return
    lieux.append({
        "id": id_val, "nom": nom, "categorie": cat, "sous_categorie": scat,
        "latitude": lat, "longitude": lon, "adresse": adr, "quartier": qrt,
        "description_fr": d_fr, "description_en": d_en, "description_ar": d_ar,
        "note_moyenne": note, "nb_avis": avis, "prix_entree_mad": prix, "gratuit": gratuit,
        "horaires": {
            "lundi": "09:00-18:00", "mardi": "09:00-18:00", "mercredi": "09:00-18:00",
            "jeudi": "09:00-18:00", "vendredi": "09:00-18:00", "samedi": "09:00-20:00", "dimanche": "09:00-20:00"
        },
        "duree_visite_min": duree_min, "duree_visite_max": duree_max,
        "tags": tags, "saison_recommandee": saison, "accessibilite_pmr": pmr,
        "image_url": img, "site_web": web, "telephone": tel, "source_donnee": "Google Places + OpenStreetMap"
    })

# 8 MARCHES ET SOUKS (Suite)
add_lieu("lieu_041", "Marché au Poisson du Port", "marche_souk", "marche_frais", 35.7890, -5.8050, "Port de Pêche, Tanger 90000, Maroc", "Port",
"Le marché au poisson du port de pêche de Tanger est une expérience viscérale et mémorable pour les lève-tôt. Dès l'aube, les chalutiers et les petites barques bleues traditionnelles déchargent la pêche de la nuit. L'agitation y est à son comble : enchères criées à la volée, marchands ambulants, restaurateurs négociant âprement, et chats affamés guettant la moindre aubaine. C'est un spectacle chaotique, très odorant et incroyablement vivant. Les petits restaurants populaires juste à côté vous proposeront de griller instantanément votre poisson fraîchement acheté pour un petit-déjeuner inoubliable.",
"The fish market at the fishing port of Tangier is a visceral and memorable experience for early risers. At dawn, trawlers and small traditional blue boats unload the night's catch. The hustle and bustle is at its peak: auctions shouted on the fly, street vendors, restaurateurs negotiating fiercely, and hungry cats watching for the slightest opportunity. It is a chaotic, highly odorous, and incredibly lively spectacle. The small popular restaurants right next door will offer to instantly grill your freshly bought fish for an unforgettable breakfast.",
"يعتبر سوق السمك في ميناء الصيد بطنجة تجربة عميقة ولا تُنسى لأولئك الذين يستيقظون باكراً. عند الفجر، تقوم سفن الصيد والقوارب الزرقاء التقليدية الصغيرة بتفريغ صيد الليل. يصل الصخب والضجيج إلى ذروته: مزادات بصوت عالٍ، وباعة متجولون، وأصحاب مطاعم يتفاوضون بشراسة، وقطط جائعة تترقب أدنى فرصة. إنه مشهد فوضوي ذو رائحة نفاذة للغاية ومفعم بالحيوية بشكل لا يصدق. ستعرض عليك المطاعم الشعبية الصغيرة المجاورة شواء أسماكك المشتراة حديثاً على الفور لتناول وجبة فطور لا تُنسى على الإطلاق.",
4.5, 850, 0, True, 45, 90, ["marche", "poisson", "port", "authentique"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?fishmarket,port,tangier", None, None)

add_lieu("lieu_042", "Marché de Sidi Bouabid", "marche_souk", "marche_couvert", 35.7840, -5.8110, "Place du 9 Avril, Tanger 90000, Maroc", "Centre-ville",
"Juste à côté de la fameuse mosquée qui lui donne son nom, ce petit marché couvert spécialisé est l'un des secrets les mieux gardés pour les amateurs de vannerie et d'artisanat rural. Moins frénétique que le Grand Socco voisin, on y trouve d'excellentes affaires sur les chapeaux de paille typiques (taraza), les couffins tissés à la main, les cuillères en bois de citronnier et une incroyable variété d'épices fraîches et de fruits secs. L'accueil y est chaleureux, les couleurs éclatantes, et la pression commerciale bien moindre que dans les rues principales de la médina.",
"Right next to the famous mosque that gives it its name, this small specialized covered market is one of the best-kept secrets for lovers of basketry and rural crafts. Less frantic than the neighboring Grand Socco, you can find excellent deals on typical straw hats (taraza), hand-woven baskets, lemon wood spoons, and an incredible variety of fresh spices and dried fruits. The welcome is warm, the colors vibrant, and the commercial pressure much lower than in the main streets of the medina.",
"بجوار المسجد الشهير الذي يمنحه اسمه مباشرة، يعد هذا السوق المغطى الصغير المتخصص أحد أفضل الأسرار المحفوظة لعشاق صناعة السلال والحرف الريفية البسيطة. وهو أقل جنوناً وصخباً من ساحة السوق الكبير المجاورة، ويمكنك العثور فيه على صفقات ممتازة على قبعات القش النموذجية (الترازة)، والسلال المنسوجة يدوياً، والملاعق المصنوعة من خشب الليمون، ومجموعة مذهلة من التوابل الطازجة والفواكه المجففة. الترحيب هناك حار جداً، والألوان نابضة بالحياة، والضغط التجاري أقل بكثير مما هو عليه في الشوارع الرئيسية للمدينة العتيقة.",
4.4, 450, 0, True, 20, 45, ["marche", "artisanat", "vannerie", "calme"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?market,baskets,morocco", None, None)

# 8 SITES ARCHEOLOGIQUES ET MUSEES
add_lieu("lieu_043", "Nécropole Phénicienne de Marshan", "site_archeologique", "necropole", 35.7920, -5.8230, "Avenue Hadj Mohamed Tazi, Tanger 90000, Maroc", "Marshan",
"Perchée sur une falaise majestueuse face au détroit, cette étonnante nécropole phénico-punique taillée à même la roche date de l'Antiquité (environ IVe siècle av. J.-C.). Une petite centaine de tombes sont directement creusées dans le sol calcaire brut. Si le site archéologique n'est ni clôturé ni formellement aménagé comme un musée traditionnel, son accès entièrement libre en fait un lieu unique. S'asseoir au bord de l'une de ces tombes millénaires pour contempler l'océan Atlantique et l'Espagne au loin est une expérience d'une poésie mélancolique rare, très prisée des jeunes Tangérois au crépuscule.",
"Perched on a majestic cliff facing the strait, this astonishing Phoenician-Punic necropolis carved straight into the rock dates back to Antiquity (around the 4th century BC). About a hundred tombs are directly dug into the raw limestone ground. Although the archaeological site is neither fenced nor formally arranged like a traditional museum, its entirely free access makes it a unique place. Sitting on the edge of one of these millennial tombs to contemplate the Atlantic Ocean and Spain in the distance is an experience of rare melancholic poetry, highly prized by young Tangier residents at dusk.",
"تقع هذه المقبرة الفينيقية البونيقية المذهلة والمنحوتة في الصخر على جرف مهيب يواجه المضيق، ويعود تاريخها إلى العصور القديمة (حوالي القرن الرابع قبل الميلاد). تم حفر حوالي مائة مقبرة مباشرة في الأرض الجيرية الخام. ورغم أن الموقع الأثري غير مسيج أو مرتب رسمياً مثل المتاحف التقليدية، إلا أن إمكانية الوصول إليه مجاناً بالكامل تجعله مكاناً فريداً. إن الجلوس على حافة أحد هذه القبور التي تعود إلى آلاف السنين لتأمل المحيط الأطلسي وإسبانيا في الأفق هي تجربة ذات شعر كئيب ونادر، وتحظى بتقدير كبير من قبل شباب طنجة عند الغسق.",
4.5, 1200, 0, True, 30, 60, ["archeologie", "panorama", "histoire", "coucher_soleil"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?ruins,cliff,morocco", None, None)

add_lieu("lieu_044", "Grottes d'Hercule", "site_archeologique", "grotte", 35.7600, -5.9390, "Route des Grottes, Cap Spartel, Tanger 90000, Maroc", "Achakkar",
"Mêlant archéologie et mythologie gréco-romaine, ces grottes spectaculaires partiellement naturelles et partiellement creusées par l'homme sont l'une des attractions les plus célèbres de Tanger. La légende raconte que le héros Hercule s'y serait reposé après avoir séparé l'Europe de l'Afrique. L'aspect le plus iconique du site est sa grande ouverture donnant sur l'océan, dont la forme inversée ressemble étonnamment à la carte du continent africain. Récemment restaurées, les grottes offrent une plongée fraîche et mystérieuse, particulièrement impressionnante lorsque les puissantes vagues atlantiques viennent se fracasser contre les parois intérieures.",
"Mixing archaeology and Greco-Roman mythology, these spectacular, partially natural and partially man-made caves are one of Tangier's most famous attractions. Legend has it that the hero Hercules rested here after separating Europe from Africa. The most iconic aspect of the site is its large opening looking out to the ocean, whose inverted shape strikingly resembles the map of the African continent. Recently restored, the caves offer a cool and mysterious dive, particularly impressive when the powerful Atlantic waves crash against the inner walls.",
"تجمع هذه الكهوف المذهلة بين علم الآثار والأساطير اليونانية الرومانية، وهي طبيعية جزئياً ومحفورة بواسطة الإنسان جزئياً، وتعد واحدة من أشهر مناطق الجذب في طنجة. وتقول الأسطورة أن البطل هرقل استراح فيها بعد فصل أوروبا عن إفريقيا. الجانب الأكثر أيقونية في الموقع هو فتحته الكبيرة المطلة على المحيط، والتي يشبه شكلها المقلوب بشكل لافت للنظر خريطة القارة الأفريقية. تم ترميم الكهوف مؤخراً، وهي توفر غوصاً بارداً وغامضاً، وتكون مثيرة للإعجاب بشكل خاص عندما تتحطم أمواج الأطلسي القوية ضد الجدران الداخلية للمغارة.",
4.6, 5600, 10, False, 30, 60, ["archeologie", "nature", "mythologie", "ocean"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?cave,ocean,morocco", None, None)

add_lieu("lieu_045", "Ruines Romaines de Cotta", "site_archeologique", "ruines_romaines", 35.7550, -5.9380, "Plage d'Achakkar, Tanger 90000, Maroc", "Achakkar",
"Situées à quelques dizaines de mètres de la plage près des Grottes d'Hercule, les ruines antiques de Cotta sont les vestiges remarquables d'un ancien complexe industriel romain datant du IIe ou IIIe siècle. Ce site archéologique à ciel ouvert servait principalement à la salaison du poisson et à la production du célèbre garum, un condiment très prisé dans tout l'Empire romain. Moins visitées que d'autres sites majeurs, les ruines permettent une promenade tranquille parmi d'anciens bassins de pierre, des vestiges de thermes et un temple, offrant une perspective fascinante sur l'économie antique de la région.",
"Located a few dozen meters from the beach near the Caves of Hercules, the ancient ruins of Cotta are the remarkable remains of an ancient Roman industrial complex dating from the 2nd or 3rd century. This open-air archaeological site was primarily used for fish salting and the production of the famous garum, a highly prized condiment throughout the Roman Empire. Less visited than other major sites, the ruins allow for a quiet stroll among ancient stone basins, remains of thermal baths, and a temple, offering a fascinating perspective on the region's ancient economy.",
"تقع أطلال كوتا القديمة على بعد بضع عشرات من الأمتار من الشاطئ بالقرب من مغارات هرقل، وهي بقايا رائعة لمجمع صناعي روماني قديم يعود تاريخه إلى القرن الثاني أو الثالث. تم استخدام هذا الموقع الأثري في الهواء الطلق في المقام الأول لتمليح الأسماك وإنتاج الغاروم الشهير، وهو بهار يحظى بتقدير كبير في جميع أنحاء الإمبراطورية الرومانية. تسمح الأطلال، التي يزورها عدد أقل من المواقع الرئيسية الأخرى، بنزهة هادئة بين الأحواض الحجرية القديمة وبقايا الحمامات الحرارية والمعبد، مما يوفر منظوراً رائعاً للاقتصاد القديم في المنطقة.",
4.1, 280, 0, True, 20, 45, ["archeologie", "histoire", "romain", "nature"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?roman,ruins,morocco", None, None)

add_lieu("lieu_046", "Musée de la Kasbah (Antiquités)", "musee", "musee_histoire", 35.7876, -5.8126, "Place de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"Installé dans l'ancien palais résidentiel du Sultan (Dar el Makhzen), ce musée exceptionnel est consacré aux cultures méditerranéennes et à l'histoire riche du nord du Maroc, de la préhistoire jusqu'au XIXe siècle. L'architecture du bâtiment est tout aussi fascinante que la collection qu'il abrite. En parcourant ses luxueuses salles palatiales aux plafonds de cèdre richement sculptés et ses superbes jardins andalous intérieurs, le visiteur découvre des artefacts archéologiques romains saisissants, des céramiques anciennes et des cartes historiques illustrant le rôle clé de Tanger comme porte incontournable entre deux continents.",
"Housed in the former residential palace of the Sultan (Dar el Makhzen), this exceptional museum is dedicated to Mediterranean cultures and the rich history of northern Morocco, from prehistory to the 19th century. The architecture of the building is just as fascinating as the collection it houses. Wandering through its luxurious palatial rooms with richly carved cedar ceilings and its superb inner Andalusian gardens, the visitor discovers striking Roman archaeological artifacts, ancient ceramics, and historical maps illustrating Tangier's key role as an essential gateway between two continents.",
"يقع هذا المتحف الاستثنائي في القصر السكني السابق للسلطان (دار المخزن)، وهو مخصص لثقافات البحر الأبيض المتوسط والتاريخ الغني لشمال المغرب، من عصور ما قبل التاريخ حتى القرن التاسع عشر. لا تقل هندسة المبنى روعة عن المجموعة القيمة التي يضمها. عند التجول في قاعاته الملكية الفاخرة ذات الأسقف المصنوعة من خشب الأرز المنحوتة ببذخ وحدائقه الأندلسية الداخلية الرائعة، يكتشف الزائر قطعاً أثرية رومانية مذهلة، وخزفيات قديمة، وخرائط تاريخية توضح دور طنجة الرئيسي كبوابة لا غنى عنها بين قارتين عظيمتين.",
4.6, 2100, 20, False, 60, 120, ["musee", "histoire", "archeologie", "culture"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?museum,artifacts,morocco", None, None)

add_lieu("lieu_047", "Musée de la Légation Américaine", "musee", "musee_histoire", 35.7832, -5.8118, "8 Chemin des Amoureux, Tanger 90000, Maroc", "Médina",
"Ce magnifique palais mauresque situé au cœur de la médina est la toute première propriété diplomatique acquise par les États-Unis à l'étranger, symbolisant le fait que le Maroc fut le premier pays au monde à reconnaître officiellement l'indépendance américaine. Aujourd'hui transformé en un musée culturel et historique de premier plan, il abrite une impressionnante collection de peintures envoûtantes, dont la célèbre 'Mona Lisa marocaine' peinte par Marguerite McBey. Il propose également une aile entière dédiée à l'auteur Paul Bowles et sert de centre d'études florissant. Une visite incontournable.",
"This magnificent Moorish palace located in the heart of the medina is the very first diplomatic property acquired by the United States abroad, symbolizing the fact that Morocco was the first country in the world to officially recognize American independence. Today transformed into a leading cultural and historical museum, it houses an impressive collection of captivating paintings, including the famous 'Moroccan Mona Lisa' painted by Marguerite McBey. It also features an entire wing dedicated to author Paul Bowles and serves as a thriving study center. An absolute must-visit.",
"هذا القصر الموريسكي الرائع الواقع في قلب المدينة العتيقة هو أول عقار دبلوماسي تحصل عليه الولايات المتحدة في الخارج على الإطلاق، وهو يرمز إلى حقيقة أن المغرب كان أول دولة في العالم تعترف رسمياً بالاستقلال الأمريكي. تحول اليوم إلى متحف ثقافي وتاريخي رائد، ويضم مجموعة رائعة ومثيرة للإعجاب من اللوحات الآسرة، بما في ذلك 'الموناليزا المغربية' الشهيرة التي رسمتها مارغريت ماكبي. كما يضم جناحاً كاملاً مخصصاً للمؤلف بول بولز ويعمل كمركز دراسات مزدهر. إنها زيارة ضرورية ولا غنى عنها لأي مهتم بالتاريخ.",
4.8, 1400, 20, False, 45, 90, ["musee", "histoire", "diplomatie", "art"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?museum,painting,tangier", None, None)

add_lieu("lieu_048", "Musée de la Fondation Lorin", "musee", "musee_art", 35.7852, -5.8108, "Rue Touahine, Médina, Tanger 90000, Maroc", "Médina",
"Installé dans le cadre charmant d'une ancienne synagogue abandonnée de la rue Touahine, le musée de la Fondation Lorin est un trésor caché pour les amateurs de nostalgie et d'histoire locale. Il présente une collection riche et étonnante de photographies en noir et blanc, d'articles de journaux jaunis, d'anciennes affiches publicitaires et de documents rares illustrant la vie politique, sportive et sociale de Tanger entre les années 1930 et 1960. La visite, souvent accompagnée par le récit passionné du gardien, offre une plongée fascinante et émouvante dans l'âge d'or révolu et trépidant de la ville internationale.",
"Housed in the charming setting of an abandoned former synagogue on Rue Touahine, the Lorin Foundation Museum is a hidden treasure for lovers of nostalgia and local history. It presents a rich and astonishing collection of black and white photographs, yellowed newspaper articles, old advertising posters, and rare documents illustrating the political, sports, and social life of Tangier between the 1930s and 1960s. The visit, often accompanied by the passionate storytelling of the caretaker, offers a fascinating and moving dive into the bygone and thrilling golden age of the international city.",
"يقع متحف مؤسسة لورين في بيئة ساحرة لكنيس يهودي مهجور سابق في شارع الطواحين، وهو كنز مخفي لعشاق الحنين إلى الماضي والتاريخ المحلي. يعرض مجموعة غنية ومذهلة من الصور الفوتوغرافية بالأبيض والأسود، والمقالات الصحفية الصفراء، والملصقات الإعلانية القديمة، والوثائق النادرة التي توضح الحياة السياسية والرياضية والاجتماعية في طنجة بين ثلاثينيات وستينيات القرن العشرين. تقدم الزيارة، التي غالباً ما يرافقها السرد العاطفي والشغوف للحارس، غوصاً رائعاً ومؤثراً في العصر الذهبي المثير والمنقضي للمدينة الدولية.",
4.5, 420, 0, True, 30, 60, ["musee", "histoire_locale", "photographie", "nostalgie"], ["printemps", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?photograph,vintage,morocco", None, None)

add_lieu("lieu_049", "Musée d'Art Contemporain (MACVT)", "musee", "musee_art", 35.7830, -5.8150, "Rue de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"Le Musée d'Art Contemporain de la Ville de Tanger (MACVT), récemment inauguré dans l'ancienne prison historique de la Kasbah brillamment réhabilitée, est le nouveau pôle culturel majeur de la ville. Les sombres et anciennes cellules pénitentiaires, avec leurs murs épais, contrastent désormais avec les toiles vibrantes et avant-gardistes des artistes marocains et internationaux contemporains qu'elles exposent. Ce musée offre une plateforme d'expression audacieuse pour les jeunes talents régionaux et prouve que Tanger reste une muse éternelle pour la création artistique moderne.",
"The Museum of Contemporary Art of the City of Tangier (MACVT), recently inaugurated in the brilliantly rehabilitated historic former prison of the Kasbah, is the city's new major cultural hub. The dark, ancient penitentiary cells, with their thick walls, now contrast with the vibrant and avant-garde canvases of contemporary Moroccan and international artists they display. This museum offers a bold platform of expression for young regional talents and proves that Tangier remains an eternal muse for modern artistic creation.",
"يُعد متحف الفن المعاصر لمدينة طنجة (MACVT)، الذي تم افتتاحه مؤخراً في السجن التاريخي السابق للقصبة والذي تم إعادة تأهيله ببراعة، المركز الثقافي الرئيسي الجديد في المدينة. تتناقض زنزانات السجن القديمة المظلمة، بجدرانها السميكة للغاية، الآن مع اللوحات النابضة بالحياة والرائدة للفنانين المغاربة والدوليين المعاصرين التي تعرضها. يوفر هذا المتحف منصة تعبير جريئة للمواهب الإقليمية الشابة المبدعة ويثبت أن طنجة تظل ملهمة أبدية للإبداع الفني الحديث والمتجدد.",
4.6, 310, 20, False, 45, 90, ["musee", "art_contemporain", "culture", "peinture"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?gallery,art,morocco", None, None)

add_lieu("lieu_050", "Musée Forbes (Collections de Dar el Makhzen)", "musee", "musee_collection", 35.7880, -5.8210, "Palais Mendoub, Tanger 90000, Maroc", "Marshan",
"Jadis propriété du célèbre magnat américain Malcolm Forbes, ce magnifique palais de Marshan abritait autrefois l'une des plus grandes collections de soldats de plomb au monde, mise en scène dans des reconstitutions de batailles historiques, de Waterloo à Dien Bien Phu. Si la collection monumentale de plus de 115 000 figurines a depuis été dispersée aux enchères, l'histoire rocambolesque de ce lieu, qui a accueilli l'une des fêtes d'anniversaire les plus somptueuses et extravagantes du XXe siècle, continue d'intriguer. Le lieu accueille aujourd'hui occasionnellement des expositions privées prestigieuses et le bâtiment lui-même reste une légende de la ville.",
"Once owned by the famous American magnate Malcolm Forbes, this magnificent Marshan palace formerly housed one of the largest collections of lead soldiers in the world, staged in reconstructions of historical battles, from Waterloo to Dien Bien Phu. Although the monumental collection of over 115,000 figurines has since been dispersed at auction, the incredible history of this place, which hosted one of the most sumptuous and extravagant birthday parties of the 20th century, continues to intrigue. The venue now occasionally hosts prestigious private exhibitions, and the building itself remains a city legend.",
"كان هذا القصر الرائع في المرشان، الذي كان مملوكاً في السابق لقطب الإعلام الأمريكي الشهير مالكولم فوربس، يضم في الماضي واحدة من أكبر مجموعات الجنود الرصاص في العالم بأسره، والتي تم عرضها في عمليات إعادة بناء دقيقة للمعارك التاريخية، من واترلو إلى ديان بيان فو. وعلى الرغم من أن المجموعة الضخمة التي تضم أكثر من 115 ألف تمثال قد تم بيعها منذ ذلك الحين في المزاد، إلا أن التاريخ المذهل لهذا المكان، الذي استضاف واحدة من أفخم حفلات أعياد الميلاد وأكثرها إسرافاً في القرن العشرين، لا يزال يثير الفضول. يستضيف المكان الآن معارض خاصة مرموقة في بعض الأحيان، ويبقى المبنى بحد ذاته أسطورة من أساطير المدينة.",
4.2, 180, 0, True, 20, 45, ["histoire", "insolite", "collection", "palais"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?mansion,museum,tangier", None, None)

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(lieux, f, ensure_ascii=False, indent=2)

print(f'Done! Total {len(lieux)} lieux saved to {filepath}')
