import json
faqs = []
def add(cat,intent,qf,qe,qa,rf,re,ra,tags,pri):
    faqs.append({"id":f"faq_{len(faqs)+1:03d}","categorie":cat,"intention":intent,"question_fr":qf,"question_en":qe,"question_ar":qa,"reponse_fr":rf,"reponse_en":re,"reponse_ar":ra,"tags":tags,"priorite":pri})

# TRANSPORT (8)
add("transport","info_aeroport","Comment aller de l'aéroport au centre-ville ?","How to get from the airport to the city center?","كيف أصل من المطار إلى وسط المدينة؟","L'aéroport Ibn Battouta est à 12 km. Options : Grand taxi (150-200 MAD, 20 min), bus ALSA L15 (5 MAD, 45 min), VTC Careem/InDrive (80-120 MAD).","Ibn Battouta Airport is 12 km away. Options: Grand taxi (150-200 MAD, 20 min), ALSA bus L15 (5 MAD, 45 min), ride-hailing Careem/InDrive (80-120 MAD).","مطار ابن بطوطة على بعد 12 كم. الخيارات: سيارة أجرة كبيرة (150-200 درهم)، حافلة ألسا L15 (5 دراهم)، تطبيق كريم/إندرايف (80-120 درهم).",["aeroport","taxi","bus"],1)
add("transport","taxi_fonctionnement","Comment fonctionnent les taxis à Tanger ?","How do taxis work in Tangier?","كيف تعمل سيارات الأجرة في طنجة؟","Petits taxis bleus (en ville, compteur, 3 places). Grands taxis Mercedes (interurbain, partagés). Insistez sur le compteur. Supplément nuit 50% après 20h.","Blue petit taxis (in-city, meter, 3 seats). Grand taxis Mercedes (intercity, shared). Insist on the meter. 50% night supplement after 8pm.","سيارات أجرة صغيرة زرقاء (داخل المدينة، عداد، 3 مقاعد). سيارات أجرة كبيرة مرسيدس (بين المدن، مشتركة). أصر على العداد.",["taxi","transport"],1)
add("transport","tgv_info","Comment prendre le TGV depuis Tanger ?","How to take the TGV from Tangier?","كيف آخذ القطار فائق السرعة من طنجة؟","Le TGV Al Boraq relie Tanger à Casablanca en 2h10. Gare Tanger Ville. Réservez sur oncf.ma. Tarifs : 149 MAD (éco) à 249 MAD (1ère).","Al Boraq TGV connects Tangier to Casablanca in 2h10. Tanger Ville station. Book at oncf.ma. Fares: 149 MAD (economy) to 249 MAD (1st class).","قطار البراق يربط طنجة بالدار البيضاء في ساعتين و10 دقائق. محطة طنجة المدينة. احجز على oncf.ma.",["tgv","train","transport"],1)
add("transport","ferry_espagne","Comment aller en Espagne par ferry ?","How to get to Spain by ferry?","كيف أذهب إلى إسبانيا بالعبّارة؟","Ferry Tanger Med-Tarifa (35 min, FRS) ou Tanger Med-Algésiras (1h30, Balearia). Réservez en avance en été. Port Tanger Med à 50 km de la ville.","Ferry Tanger Med-Tarifa (35 min, FRS) or Tanger Med-Algeciras (1h30, Balearia). Book ahead in summer. Tanger Med port is 50 km from city.","عبّارة طنجة المتوسط-طريفة (35 دقيقة) أو طنجة المتوسط-الجزيرة الخضراء (ساعة و30 دقيقة). احجز مسبقاً في الصيف.",["ferry","espagne","transport"],1)
add("transport","bus_urbain","Comment utiliser le bus urbain ?","How to use the urban bus?","كيف أستخدم الحافلة الحضرية؟","Bus ALSA, ticket 5 MAD à bord. Lignes principales : L1 (Centre-Médina), L5 (Cap Spartel), L9 (Corniche). Fréquence 15-30 min.","ALSA buses, 5 MAD ticket on board. Main lines: L1 (Center-Medina), L5 (Cape Spartel), L9 (Corniche). Frequency 15-30 min.","حافلات ألسا، تذكرة 5 دراهم. الخطوط الرئيسية: L1 (المركز-المدينة)، L5 (رأس سبارطيل)، L9 (الكورنيش).",["bus","transport"],2)
add("transport","vtc_app","Quelles applications VTC sont disponibles ?","What ride-hailing apps are available?","ما تطبيقات النقل المتوفرة؟","Careem et InDrive sont les plus utilisés à Tanger. Prix estimé à l'avance. Paiement en espèces ou carte. Plus sûr que les taxis classiques.","Careem and InDrive are most used in Tangier. Price estimated in advance. Cash or card payment. Safer than regular taxis.","كريم وإندرايف الأكثر استخداماً في طنجة. السعر محدد مسبقاً. الدفع نقداً أو بالبطاقة.",["vtc","application","transport"],2)
add("transport","chefchaouen_trajet","Comment aller à Chefchaouen depuis Tanger ?","How to get to Chefchaouen from Tangier?","كيف أذهب إلى شفشاون من طنجة؟","Bus CTM (60 MAD, 3h), Grand taxi partagé (80-100 MAD, 2h30), excursion organisée (500-800 MAD/jour), ou location de voiture.","CTM bus (60 MAD, 3h), shared Grand taxi (80-100 MAD, 2h30), organized day trip (500-800 MAD/day), or car rental.","حافلة CTM (60 درهم، 3 ساعات)، سيارة أجرة كبيرة مشتركة (80-100 درهم)، رحلة منظمة (500-800 درهم/يوم).",["chefchaouen","excursion"],2)
add("transport","location_voiture","Peut-on louer une voiture à Tanger ?","Can you rent a car in Tangier?","هل يمكن استئجار سيارة في طنجة؟","Oui, agences à l'aéroport et en ville (Europcar, Hertz, Avis). À partir de 300 MAD/jour. Permis international recommandé. Attention à la circulation dense.","Yes, agencies at airport and in town (Europcar, Hertz, Avis). From 300 MAD/day. International license recommended. Watch out for dense traffic.","نعم، وكالات في المطار والمدينة. ابتداءً من 300 درهم/يوم. رخصة دولية مستحسنة.",["voiture","location"],3)

# LIEUX (12)
add("lieux","top_attractions","Quels sont les incontournables de Tanger ?","What are the must-see attractions in Tangier?","ما هي المعالم التي لا يمكن تفويتها في طنجة؟","Les incontournables : Kasbah, Grottes d'Hercule, Cap Spartel, Médina, Terrasse des Paresseux, Café Hafa, Grand Socco et Dar el Makhzen.","Must-sees: Kasbah, Caves of Hercules, Cape Spartel, Medina, Terrace of the Lazy, Café Hafa, Grand Socco and Dar el Makhzen.","المعالم الأساسية: القصبة، مغارات هرقل، رأس سبارطيل، المدينة القديمة، مصطبة الكسالى، مقهى الحافة، السوق الكبير ودار المخزن.",["attractions","tourisme"],1)
add("lieux","medina_visite","Comment visiter la médina sans se perdre ?","How to visit the medina without getting lost?","كيف أزور المدينة القديمة دون أن أضيع؟","Prenez un guide officiel (200 MAD/3h) ou suivez les panneaux directionnels. Repérez le Grand Socco comme point de repère. Évitez les faux guides.","Hire an official guide (200 MAD/3h) or follow directional signs. Use Grand Socco as a landmark. Avoid unofficial guides.","استعن بمرشد رسمي (200 درهم/3 ساعات) أو اتبع اللافتات. استخدم السوق الكبير كنقطة مرجعية.",["medina","guide"],1)
add("lieux","grottes_hercule","Comment accéder aux Grottes d'Hercule ?","How to access the Caves of Hercules?","كيف أصل إلى مغارات هرقل؟","À 14 km du centre. Taxi (100-150 MAD aller), ou combinez avec Cap Spartel. Entrée 10 MAD. Ouvert 9h-18h tous les jours.","14 km from center. Taxi (100-150 MAD one way), or combine with Cape Spartel. Entry 10 MAD. Open 9am-6pm daily.","على بعد 14 كم من المركز. سيارة أجرة (100-150 درهم ذهاب). تذكرة 10 دراهم. مفتوح يومياً 9-18.",["grottes","hercule","excursion"],1)
add("lieux","cap_spartel","Que voir au Cap Spartel ?","What to see at Cape Spartel?","ماذا أرى في رأس سبارطيل؟","Le phare historique (1864), la jonction Atlantique-Méditerranée, coucher de soleil spectaculaire. Gratuit. Combinez avec les Grottes d'Hercule et Plage Achakkar.","Historic lighthouse (1864), Atlantic-Mediterranean junction, spectacular sunset. Free. Combine with Caves of Hercules and Achakkar Beach.","المنارة التاريخية (1864)، ملتقى الأطلسي والمتوسط، غروب مذهل. مجاني. اجمعها مع مغارات هرقل وشاطئ أشقار.",["cap_spartel","phare","coucher_soleil"],1)
add("lieux","kasbah_musee","Quels musées visiter dans la Kasbah ?","What museums to visit in the Kasbah?","ما المتاحف التي يمكن زيارتها في القصبة؟","Dar el Makhzen (musée archéologique, 20 MAD), Musée de la Kasbah (art marocain). Fermés le mardi. Prévoir 2h pour les deux.","Dar el Makhzen (archaeological museum, 20 MAD), Kasbah Museum (Moroccan art). Closed Tuesdays. Allow 2h for both.","دار المخزن (متحف أثري، 20 درهم)، متحف القصبة (فن مغربي). مغلقان يوم الثلاثاء.",["musee","kasbah","culture"],1)
add("lieux","plages_tanger","Quelles sont les meilleures plages ?","What are the best beaches?","ما هي أفضل الشواطئ؟","Plage Municipale (urbaine, accessible), Achakkar (surf, sauvage), Sidi Kankouch (crique isolée), Malabata (vue Gibraltar). Baignade juin-septembre.","Municipal Beach (urban, accessible), Achakkar (surf, wild), Sidi Kankouch (isolated cove), Malabata (Gibraltar view). Swimming June-September.","الشاطئ البلدي (حضري)، أشقار (ركوب أمواج)، سيدي كنكوش (خليج منعزل)، ملاباطا (إطلالة جبل طارق).",["plage","baignade","mer"],1)
add("lieux","cafe_hafa","Pourquoi le Café Hafa est-il célèbre ?","Why is Café Hafa famous?","لماذا مقهى الحافة مشهور؟","Fondé en 1921, perché sur les falaises face au détroit. Fréquenté par les Beatles et Rolling Stones. Célèbre pour son thé à la menthe et coucher de soleil.","Founded in 1921, perched on cliffs facing the strait. Frequented by the Beatles and Rolling Stones. Famous for mint tea and sunset.","تأسس عام 1921 على الجرف أمام المضيق. ارتاده بيتلز ورولينغ ستونز. مشهور بالشاي بالنعناع والغروب.",["cafe","histoire","coucher_soleil"],2)
add("lieux","terrasse_paresseux","Où avoir la meilleure vue sur le détroit ?","Where to get the best strait view?","أين أجد أفضل إطلالة على المضيق؟","Terrasse des Paresseux (centre-ville, gratuit), Belvédère de la Kasbah, Colline du Charf (360°), et Café Hafa. Idéal au coucher du soleil.","Terrace of the Lazy (city center, free), Kasbah Belvedere, Charf Hill (360°), and Café Hafa. Best at sunset.","مصطبة الكسالى (مجاني)، مرقب القصبة، تلة الشرف (360°)، ومقهى الحافة. الأفضل عند الغروب.",["panorama","vue","coucher_soleil"],2)
add("lieux","marche_central","Quand visiter le Marché Central ?","When to visit the Central Market?","متى أزور السوق المركزي؟","Le matin (7h-14h) pour la fraîcheur. Poisson, épices, olives, fruits. Fermé l'après-midi. Ambiance authentique et colorée.","Morning (7am-2pm) for freshness. Fish, spices, olives, fruits. Closed in the afternoon. Authentic and colorful atmosphere.","الصباح (7-14) للطزاجة. سمك، بهارات، زيتون، فواكه. مغلق بعد الظهر. أجواء أصيلة وملونة.",["marche","gastronomie","local"],2)
add("lieux","lieux_gratuits","Quels sites sont gratuits à Tanger ?","What sites are free in Tangier?","ما المواقع المجانية في طنجة؟","Grand Socco, Petit Socco, Terrasse des Paresseux, Cap Spartel, Jardins Mendoubia, plages, Médina (extérieur), Belvédère Kasbah.","Grand Socco, Petit Socco, Terrace of the Lazy, Cape Spartel, Mendoubia Gardens, beaches, Medina (exterior), Kasbah Belvedere.","السوق الكبير، السوق الداخل، مصطبة الكسالى، رأس سبارطيل، حدائق المندوبية، الشواطئ، المدينة القديمة.",["gratuit","budget","tourisme"],2)
add("lieux","quartier_marshan","Que voir dans le quartier Marshan ?","What to see in the Marshan district?","ماذا أرى في حي المرشان؟","Café Hafa, Parc Perdicaris, Villa Harris, Palais du Mendoub, et la vue panoramique sur le détroit. Quartier résidentiel historique.","Café Hafa, Perdicaris Park, Villa Harris, Mendoub Palace, and panoramic strait views. Historic residential district.","مقهى الحافة، حديقة بيرديكاريس، فيلا هاريس، قصر المندوب، وإطلالات بانورامية على المضيق.",["marshan","quartier","promenade"],3)
add("lieux","ibn_battuta","Qui était Ibn Battuta et son lien avec Tanger ?","Who was Ibn Battuta and his link to Tangier?","من كان ابن بطوطة وما علاقته بطنجة؟","Né à Tanger en 1304, plus grand voyageur médiéval. Sa tombe est dans la médina. L'aéroport et le stade portent son nom.","Born in Tangier in 1304, greatest medieval traveler. His tomb is in the medina. The airport and stadium bear his name.","ولد في طنجة عام 1304، أعظم رحالة في العصور الوسطى. ضريحه في المدينة القديمة. المطار والملعب يحملان اسمه.",["histoire","ibn_battuta","culture"],3)

# RESTAURANTS (8)
add("restaurants","plats_typiques","Quels plats typiques goûter à Tanger ?","What typical dishes to try in Tangier?","ما الأطباق النموذجية في طنجة؟","Tagine, couscous (vendredi), pastilla, harira, sardines grillées, msemen, baghrir, thé à la menthe. Street food : brochettes, babbouche, jus d'orange frais.","Tagine, couscous (Friday), pastilla, harira, grilled sardines, msemen, baghrir, mint tea. Street food: brochettes, snail soup, fresh OJ.","الطاجين، الكسكس (الجمعة)، البسطيلة، الحريرة، السردين المشوي، المسمن، البغرير، الشاي بالنعناع.",["gastronomie","plats","traditionnel"],1)
add("restaurants","restaurant_budget","Où manger bien et pas cher ?","Where to eat well on a budget?","أين آكل جيداً بسعر مناسب؟","Chez Abdou (médina, 40-60 MAD), Snack Atlas, Sandwicherie Maghreb, Souk Food Court. Les marchés centraux offrent aussi des repas à 30-50 MAD.","Chez Abdou (medina, 40-60 MAD), Snack Atlas, Sandwicherie Maghreb, Souk Food Court. Central markets also offer meals at 30-50 MAD.","عند عبدو (المدينة، 40-60 درهم)، سناك أطلس، ساندويتش المغرب، ساحة أكل السوق. الأسواق أيضاً توفر وجبات بـ30-50 درهم.",["budget","restaurant","economique"],1)
add("restaurants","resto_gastronomique","Quels restaurants gastronomiques recommandez-vous ?","What gourmet restaurants do you recommend?","ما المطاعم الراقية التي تنصحون بها؟","El Morocco Club (rooftop médina), El Korsan (hôtel El Minzah), Dar Nour (vue détroit), Nord-Pinus (bohème-chic), Maison Tingis (kasbah).","El Morocco Club (medina rooftop), El Korsan (El Minzah hotel), Dar Nour (strait view), Nord-Pinus (bohemian-chic), Maison Tingis (kasbah).","المغرب كلوب (سطح المدينة)، الكرسان (فندق المنزه)، دار النور (إطلالة المضيق)، نور-بينوس، ميزون طنجيس (القصبة).",["gastronomie","luxe","restaurant"],1)
add("restaurants","poisson_frais","Où manger du poisson frais ?","Where to eat fresh fish?","أين آكل سمكاً طازجاً؟","Le Saveur de Poisson (médina, expérience unique sans menu), Chez Hassan au Marché Central, La Playa (corniche), Fish & Chips Détroit.","Le Saveur de Poisson (medina, unique no-menu experience), Chez Hassan at Central Market, La Playa (corniche), Fish & Chips Détroit.","سافور دو بواسون (المدينة، تجربة بدون قائمة)، عند حسان في السوق المركزي، لابلايا (الكورنيش).",["poisson","fruits_de_mer","restaurant"],1)
add("restaurants","halal_vegetarien","Y a-t-il des options halal et végétariennes ?","Are there halal and vegetarian options?","هل توجد خيارات حلال ونباتية؟","Presque tous les restaurants sont halal au Maroc. Options végétariennes : La Fabrique, salades et tajines aux légumes dans la plupart des restaurants.","Almost all restaurants are halal in Morocco. Vegetarian options: La Fabrique, salads and vegetable tagines at most restaurants.","جميع المطاعم تقريباً حلال في المغرب. خيارات نباتية: لا فابريك، سلطات وطواجن خضار في معظم المطاعم.",["halal","vegetarien","regime"],2)
add("restaurants","street_food","Où trouver le meilleur street food ?","Where to find the best street food?","أين أجد أفضل طعام الشارع؟","Grand Socco (jus d'orange, msemen), Souk Food Court, stands de brochettes Rue de la Marine, marchands de babbouche (soupe d'escargots).","Grand Socco (orange juice, msemen), Souk Food Court, brochette stands on Rue de la Marine, babbouche (snail soup) vendors.","السوق الكبير (عصير البرتقال، المسمن)، ساحة أكل السوق، أكشاك المشاوي في شارع البحرية، باعة البابوش.",["street_food","local","budget"],2)
add("restaurants","brunch_cafe","Où prendre un bon brunch ou café ?","Where to get a good brunch or coffee?","أين أتناول فطوراً متأخراً أو قهوة جيدة؟","La Fabrique (brunch, café de spécialité), Café de Paris (historique), Panoramic Café (vue 360°), Café Baba (thé mythique).","La Fabrique (brunch, specialty coffee), Café de Paris (historic), Panoramic Café (360° view), Café Baba (mythical tea).","لا فابريك (فطور متأخر، قهوة مميزة)، مقهى باريس (تاريخي)، مقهى بانورامي (إطلالة 360°)، مقهى بابا (شاي أسطوري).",["cafe","brunch","petit_dejeuner"],2)
add("restaurants","reservation_conseil","Faut-il réserver dans les restaurants ?","Do you need reservations at restaurants?","هل يجب الحجز في المطاعم؟","Réservation recommandée pour : El Morocco Club, Dar Nour, Nord-Pinus, El Korsan, Le Saveur de Poisson. Pas nécessaire pour les restaurants populaires.","Reservation recommended for: El Morocco Club, Dar Nour, Nord-Pinus, El Korsan, Le Saveur de Poisson. Not needed for popular restaurants.","الحجز مستحسن في: المغرب كلوب، دار النور، نور-بينوس، الكرسان، سافور دو بواسون. غير ضروري للمطاعم الشعبية.",["reservation","conseil","restaurant"],3)

with open(r'c:\Users\HP\Documents\projet touristique\dataset\faq_part1.json','w',encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
print(f'Part 1: {len(faqs)} FAQs saved')
