import json
import os

lieux = []

def add_lieu(id_val, nom, cat, scat, lat, lon, adr, qrt, d_fr, d_en, d_ar, note, avis, prix, gratuit, duree_min, duree_max, tags, saison, pmr, img, web, tel):
    lieux.append({
        "id": id_val, "nom": nom, "categorie": cat, "sous_categorie": scat,
        "latitude": lat, "longitude": lon, "adresse": adr, "quartier": qrt,
        "description_fr": d_fr, "description_en": d_en, "description_ar": d_ar,
        "note_moyenne": note, "nb_avis": avis, "prix_entree_mad": prix, "gratuit": gratuit,
        "horaires": {
            "lundi": "09:00-18:00", "mardi": "09:00-18:00", "mercredi": "09:00-18:00",
            "jeudi": "09:00-18:00", "vendredi": "09:00-18:00", "samedi": "09:00-20:00", "dimanche": "09:00-20:00"
        },
        "duree_visite_min": duree_min, "duree_visite_max": duree_max,
        "tags": tags, "saison_recommandee": saison, "accessibilite_pmr": pmr,
        "image_url": img, "site_web": web, "telephone": tel, "source_donnee": "Google Places + OpenStreetMap"
    })

# 12 MONUMENTS ET SITES HISTORIQUES
add_lieu("lieu_001", "Kasbah de Tanger", "monument_historique", "forteresse", 35.7872, -5.8134, "Place de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"La Kasbah de Tanger est une ancienne forteresse qui domine la médina et le détroit de Gibraltar. Ce site historique majestueux, entouré de remparts centenaires, fut le centre du pouvoir politique et militaire de la ville pendant des siècles. En vous promenant dans ses ruelles pavées, vous découvrirez des portes monumentales, des palais magnifiques et des vues panoramiques à couper le souffle. C'est un lieu incontournable pour comprendre l'histoire fascinante de Tanger, carrefour des civilisations méditerranéennes et atlantiques, où chaque pierre raconte une époque révolue.",
"The Kasbah of Tangier is an ancient fortress that dominates the medina and the Strait of Gibraltar. This majestic historic site, surrounded by centuries-old ramparts, was the center of the city's political and military power for centuries. As you stroll through its cobbled streets, you will discover monumental gates, magnificent palaces, and breathtaking panoramic views. It is an absolute must-visit to understand the fascinating history of Tangier, a crossroads of Mediterranean and Atlantic civilizations, where every stone tells the story of a bygone era.",
"قصبة طنجة هي قلعة قديمة تهيمن على المدينة القديمة ومضيق جبل طارق. كان هذا الموقع التاريخي المهيب، المحاط بأسوار تعود لقرون، مركز القوة السياسية والعسكرية للمدينة لقرون عديدة. أثناء تجولك في شوارعها المرصوفة بالحصى، ستكتشف أبواباً أثرية وقصوراً رائعة وإطلالات بانورامية خلابة تخطف الأنفاس. إنها مكان لا بد من زيارته لفهم تاريخ طنجة الرائع، ملتقى الحضارات المتوسطية والأطلسية، حيث تروي كل حجرة قصة حقبة ماضية وتراث عريق لا يزال حاضراً بقوة في كل زاوية من زوايا هذا المعلم البارز.",
4.6, 3200, 0, True, 60, 120, ["histoire", "architecture", "panorama", "culture"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?kasbah,tangier,morocco", None, None)

add_lieu("lieu_002", "Grande Mosquée de Tanger", "monument_historique", "religion", 35.7845, -5.8102, "Rue de la Marine, Tanger 90000, Maroc", "Médina",
"La Grande Mosquée de Tanger, située au cœur de la médina, est un chef-d'œuvre de l'architecture islamique marocaine. Construite sur les vestiges d'une ancienne cathédrale portugaise, elle témoigne des multiples influences culturelles de la ville. Avec son minaret orné de faïences vertes et blanches, elle domine l'horizon de la vieille ville. Son impressionnante cour intérieure et ses portes en bois sculpté sont des exemples remarquables de l'artisanat local. Bien que l'entrée soit réservée aux musulmans, son extérieur magnifique attire les photographes et les passionnés d'histoire du monde entier.",
"The Great Mosque of Tangier, located in the heart of the medina, is a masterpiece of Moroccan Islamic architecture. Built on the remains of a former Portuguese cathedral, it bears witness to the city's multiple cultural influences. With its minaret adorned with green and white tiles, it dominates the skyline of the old town. Its impressive inner courtyard and carved wooden doors are remarkable examples of local craftsmanship. Although entry is restricted to Muslims, its magnificent exterior attracts photographers and history enthusiasts from all around the world.",
"الجامع الأعظم بطنجة، الواقع في قلب المدينة القديمة، هو تحفة من روائع العمارة الإسلامية المغربية. بُني على أنقاض كاتدرائية برتغالية قديمة، ليشهد على التأثيرات الثقافية المتعددة للمدينة. بمئذنته المزينة بالخزف الأخضر والأبيض، يسيطر على أفق المدينة العتيقة. ساحته الداخلية الرائعة وأبوابه الخشبية المنحوتة هي أمثلة استثنائية على الحرفية المحلية الدقيقة. ورغم أن الدخول مقتصر على المسلمين فقط، إلا أن واجهته الخارجية المذهلة تجذب المصورين وعشاق التاريخ من جميع أنحاء العالم للاستمتاع بجمال وتفاصيل هذا الصرح الديني العظيم.",
4.4, 850, 0, True, 15, 30, ["religion", "architecture", "histoire", "medina"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?mosque,tangier,morocco", None, None)

add_lieu("lieu_003", "Église Saint-Andrew", "monument_historique", "religion", 35.7842, -5.8105, "Rue d'Angleterre, Tanger 90000, Maroc", "Centre-ville",
"L'Église anglicane Saint-Andrew est l'un des monuments les plus fascinants de Tanger, illustrant parfaitement la coexistence pacifique des religions dans la ville. Consacrée en 1905, son architecture est un mélange étonnant de style mauresque et britannique, avec des inscriptions religieuses en arabe sculptées à l'intérieur. Le cimetière environnant est le lieu de repos de plusieurs personnalités historiques internationales. L'atmosphère paisible de ses jardins luxuriants offre un contraste saisissant avec l'agitation du Grand Socco tout proche, faisant de ce lieu une halte spirituelle et historique incontournable.",
"The Anglican Church of St. Andrew is one of the most fascinating monuments in Tangier, perfectly illustrating the peaceful coexistence of religions in the city. Consecrated in 1905, its architecture is a stunning blend of Moorish and British styles, featuring Arabic religious inscriptions carved inside. The surrounding cemetery is the resting place of several international historical figures. The peaceful atmosphere of its lush gardens offers a striking contrast to the hustle and bustle of the nearby Grand Socco, making this place a must-visit spiritual and historical stop.",
"كنيسة القديس أندرو الأنجليكانية هي واحدة من أكثر المعالم روعة في طنجة، وتجسد بشكل مثالي التعايش السلمي بين الأديان في المدينة. تم تكريسها في عام 1905، وهندستها المعمارية عبارة عن مزيج مذهل من الطرازين الموريسكي والبريطاني، مع نقوش دينية عربية محفورة في الداخل. المقبرة المحيطة هي مثوى للعديد من الشخصيات التاريخية الدولية البارزة. الأجواء الهادئة لحدائقها المورقة توفر تبايناً صارخاً مع صخب ساحة السوق الكبير القريبة، مما يجعل هذا المكان محطة روحية وتاريخية لا يمكن تفويتها لأي زائر.",
4.5, 920, 0, True, 30, 60, ["religion", "architecture", "histoire", "jardin"], ["printemps", "automne"], True, "https://source.unsplash.com/600x400/?church,architecture,tangier", None, None)

add_lieu("lieu_004", "Phare du Cap Spartel", "monument_historique", "phare", 35.7926, -5.9275, "Route de Cap Spartel, Tanger 90000, Maroc", "Cap Spartel",
"Le Phare du Cap Spartel est un monument emblématique situé à l'extrême nord-ouest du continent africain, marquant le point de rencontre précis entre l'océan Atlantique et la mer Méditerranée. Mis en service en 1864, il fut le premier phare du Maroc, construit à la demande des puissances étrangères pour sécuriser cette route maritime dangereuse. Récemment restauré et ouvert au public, il abrite aujourd'hui un petit musée maritime fascinant. Monter à son sommet offre une vue imprenable, particulièrement spectaculaire au coucher du soleil lorsque les deux mers se teintent d'or.",
"The Cape Spartel Lighthouse is an iconic monument located at the extreme northwest of the African continent, marking the exact meeting point between the Atlantic Ocean and the Mediterranean Sea. Commissioned in 1864, it was Morocco's first lighthouse, built at the request of foreign powers to secure this dangerous maritime route. Recently restored and opened to the public, it now houses a fascinating small maritime museum. Climbing to its top offers breathtaking views, particularly spectacular at sunset when the two seas turn golden.",
"منارة رأس سبارطيل هي معلم بارز يقع في أقصى الشمال الغربي للقارة الأفريقية، ويمثل نقطة الالتقاء الدقيقة بين المحيط الأطلسي والبحر الأبيض المتوسط. بدأ تشغيلها في عام 1864، وكانت أول منارة في المغرب، بنيت بناءً على طلب القوى الأجنبية لتأمين هذا الطريق البحري الخطير. تم ترميمها مؤخراً وفتحها للجمهور، وهي تضم اليوم متحفاً بحرياً صغيراً ورائعاً. يتيح الصعود إلى قمتها الاستمتاع بإطلالات خلابة لا مثيل لها، وتكون مذهلة بشكل خاص عند غروب الشمس عندما تتلون مياه البحرين باللون الذهبي الساحر.",
4.7, 4500, 20, False, 45, 90, ["histoire", "panorama", "nature", "musee"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?lighthouse,ocean,morocco", None, None)

add_lieu("lieu_005", "Tombeau d'Ibn Battuta", "monument_historique", "mausolee", 35.7858, -5.8120, "Rue Ibn Battouta, Médina, Tanger 90000, Maroc", "Médina",
"Le modeste mausolée d'Ibn Battuta abrite la sépulture du plus grand voyageur de l'histoire du monde islamique et médiéval. Né à Tanger en 1304, ce savant a parcouru près de 120 000 kilomètres au cours de sa vie, de l'Afrique de l'Ouest jusqu'en Chine. Situé dans une petite ruelle discrète de la médina, ce lieu de mémoire est un témoignage d'humilité par rapport à la grandeur de ses accomplissements. La visite de ce site historique permet de rendre hommage à cet explorateur légendaire dont les récits continuent de fasciner.",
"The modest mausoleum of Ibn Battuta houses the grave of the greatest traveler in the history of the Islamic and medieval world. Born in Tangier in 1304, this scholar traveled nearly 120,000 kilometers during his lifetime, from West Africa to China. Located in a small, discreet alleyway in the medina, this place of memory is a testament to humility compared to the grandeur of his achievements. Visiting this historical site is an opportunity to pay homage to this legendary explorer whose tales continue to fascinate scholars and travelers alike.",
"يضم ضريح ابن بطوطة المتواضع قبر أعظم رحالة في تاريخ العالم الإسلامي والعصور الوسطى. وُلد هذا العالم الجليل في طنجة عام 1304، وسافر حوالي 120 ألف كيلومتر خلال حياته، من غرب إفريقيا إلى الصين. يقع هذا المكان التذكاري في زقاق صغير هادئ بالمدينة القديمة، وهو شهادة على التواضع مقارنة بعظمة إنجازاته التاريخية المذهلة. تتيح زيارة هذا الموقع التاريخي الفرصة لتكريم هذا المستكشف الأسطوري الذي لا تزال كتاباته ورواياته عن أسفاره تفتن العلماء والمسافرين من جميع أنحاء العالم حتى يومنا هذا.",
4.1, 750, 0, True, 15, 30, ["histoire", "culture", "religion", "exploration"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?tomb,medina,tangier", None, None)

add_lieu("lieu_006", "Palais du Mendoub", "monument_historique", "palais", 35.7882, -5.8200, "Avenue des Ambassadeurs, Tanger 90000, Maroc", "Marshan",
"L'ancien Palais du Mendoub, situé dans le prestigieux quartier de Marshan, était la résidence officielle du représentant du Sultan pendant la période où Tanger était une zone internationale. Cette magnifique demeure entourée de jardins luxuriants est un brillant exemple de l'architecture hispano-mauresque, avec ses zelliges finement taillés, ses fontaines andalouses et ses plafonds en cèdre sculpté. Bien qu'il serve aujourd'hui de maison d'hôtes royale et que l'accès intérieur soit restreint, l'architecture extérieure et les jardins avoisinants méritent amplement le détour pour admirer ce joyau patrimonial.",
"The former Mendoub Palace, located in the prestigious Marshan district, was the official residence of the Sultan's representative during the period when Tangier was an international zone. This magnificent mansion surrounded by lush gardens is a brilliant example of Hispano-Moorish architecture, with its finely cut zelliges, Andalusian fountains, and carved cedar ceilings. Although it now serves as a royal guesthouse and interior access is restricted, the exterior architecture and neighboring gardens are well worth a visit to admire this architectural jewel.",
"قصر المندوب القديم، الواقع في حي المرشان الراقي، كان المقر الرسمي لممثل السلطان خلال الفترة التي كانت فيها طنجة منطقة دولية. يعتبر هذا القصر الرائع المحاط بالحدائق المورقة مثالاً متألقاً للهندسة المعمارية الإسبانية الموريسكية، حيث يتميز بزليجه المقطوع بدقة، ونوافيره الأندلسية، وأسقفه المصنوعة من خشب الأرز المنحوت. على الرغم من أنه يستخدم اليوم كدار ضيافة ملكية ويقتصر الدخول إلى داخله، إلا أن هندسته المعمارية الخارجية والحدائق المجاورة تستحق الزيارة بكل تأكيد للإعجاب بهذه الجوهرة المعمارية التراثية الفريدة.",
4.3, 310, 0, True, 20, 45, ["histoire", "architecture", "palais"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?palace,architecture,morocco", None, None)

add_lieu("lieu_007", "Bab Al Fahs", "monument_historique", "porte_historique", 35.7840, -5.8095, "Place du 9 Avril, Tanger 90000, Maroc", "Centre-ville",
"Bab Al Fahs est l'une des portes monumentales les plus importantes de Tanger, servant historiquement de point d'entrée principal reliant la ville nouvelle (Ville Nouvelle) à l'ancienne médina. Donnant directement sur l'effervescence du Grand Socco, cette porte ancienne en forme d'arc en plein cintre témoigne de l'évolution urbaine de la ville. Elle représente la frontière symbolique entre l'époque internationale moderne et le patrimoine arabo-andalou traditionnel. Passer sous son arche, c'est littéralement voyager dans le temps pour plonger dans l'atmosphère unique et animée de la médina.",
"Bab Al Fahs is one of the most important monumental gates of Tangier, historically serving as the main entry point connecting the new town (Ville Nouvelle) to the old medina. Opening directly onto the bustling Grand Socco, this ancient round-arched gate is a testament to the city's urban evolution. It represents the symbolic border between the modern international era and the traditional Arab-Andalusian heritage. Passing under its arch is literally traveling through time to dive into the unique and lively atmosphere of the medina.",
"باب الفحص هو واحد من أهم الأبواب الأثرية في طنجة، وكان يمثل تاريخياً نقطة الدخول الرئيسية التي تربط المدينة الجديدة (فيل نوفيل) بالمدينة القديمة. يطل هذا الباب القديم ذو القوس الدائري مباشرة على صخب ساحة السوق الكبير، ويشهد على التطور العمراني للمدينة. إنه يمثل الحدود الرمزية بين الحقبة الدولية الحديثة والتراث العربي الأندلسي التقليدي العريق. إن المرور تحت قوسه هو بمثابة السفر عبر الزمن للغوص في الأجواء الفريدة والحيوية المليئة بالألوان والأصوات داخل أزقة المدينة العتيقة.",
4.5, 1200, 0, True, 10, 20, ["histoire", "architecture", "medina", "porte"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?gate,medina,morocco", None, None)

add_lieu("lieu_008", "Bab Kasbah", "monument_historique", "porte_historique", 35.7865, -5.8130, "Quartier de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"Bab Kasbah est la porte principale permettant l'accès à la forteresse historique de la Kasbah de Tanger. Cette structure défensive massive, construite à l'époque portugaise puis renforcée par les dynasties marocaines, se dresse comme un fier rappel du passé militaire de la ville. Son architecture fortifiée, avec ses murs épais et ses créneaux, offrait une protection essentielle contre les invasions maritimes. Aujourd'hui, elle accueille les visiteurs qui s'apprêtent à découvrir les palais, musées et ruelles pittoresques de la citadelle, offrant d'excellentes opportunités photographiques.",
"Bab Kasbah is the main gate providing access to the historical fortress of the Kasbah of Tangier. This massive defensive structure, built during the Portuguese era and later reinforced by Moroccan dynasties, stands as a proud reminder of the city's military past. Its fortified architecture, with thick walls and battlements, offered essential protection against maritime invasions. Today, it welcomes visitors preparing to explore the palaces, museums, and picturesque alleys of the citadel, offering excellent photographic opportunities for architecture enthusiasts.",
"باب القصبة هو الباب الرئيسي الذي يتيح الوصول إلى قلعة قصبة طنجة التاريخية. يقف هذا الهيكل الدفاعي الضخم، الذي بني في العهد البرتغالي وتم تعزيزه لاحقاً من قبل السلالات الحاكمة المغربية، كتذكير فخور بالماضي العسكري للمدينة. وفرت هندسته المعمارية المحصنة، بأسوارها السميكة وشرفاتها الحربية، حماية أساسية ضد الغزوات البحرية. يستقبل اليوم الزوار الذين يستعدون لاكتشاف القصور والمتاحف والأزقة الخلابة للقلعة، ويوفر فرصاً ممتازة لالتقاط صور تذكارية رائعة لمحبي العمارة والتاريخ.",
4.6, 950, 0, True, 10, 20, ["histoire", "architecture", "kasbah", "porte"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?fortress,gate,tangier", None, None)

add_lieu("lieu_009", "Mosquée Sidi Bou Abid", "monument_historique", "religion", 35.7838, -5.8100, "Place du 9 Avril 1947, Tanger 90000, Maroc", "Centre-ville",
"Surplombant l'animée place du Grand Socco, la mosquée Sidi Bou Abid, construite en 1917, se distingue par son minaret octogonal exceptionnel décoré de céramiques polychromes éclatantes. Dédiée au saint patron bien-aimé de la ville, cette mosquée est un repère visuel majeur à Tanger. Ses portes majestueuses et son architecture de style mauresque classique en font un monument emblématique qui rythme la vie du quartier au son des appels à la prière. Le contraste entre le blanc immaculé de ses murs et le bleu du ciel est saisissant.",
"Overlooking the bustling Grand Socco square, the Sidi Bou Abid Mosque, built in 1917, stands out with its exceptional octagonal minaret decorated with vibrant polychrome ceramics. Dedicated to the beloved patron saint of the city, this mosque is a major visual landmark in Tangier. Its majestic doors and classic Moorish-style architecture make it an iconic monument that punctuates the life of the neighborhood to the sound of the calls to prayer. The contrast between the pristine white of its walls and the blue of the sky is striking.",
"يطل مسجد سيدي بوعبيد الذي بُني عام 1917 على ساحة السوق الكبير الصاخبة، ويتميز بمئذنته المثمنة الاستثنائية المزينة بخزف متعدد الألوان زاهي الجمال. خصص هذا المسجد للولي الصالح المحبوب في المدينة، ويعتبر معلماً بصرياً رئيسياً في طنجة. أبوابه المهيبة وهندسته المعمارية الكلاسيكية على الطراز الموريسكي تجعل منه صرحاً أيقونياً ينظم إيقاع الحياة في الحي على أصوات الأذان. التباين بين اللون الأبيض الناصع لجدرانه وزرقة السماء يوفر مشهداً رائعاً يخطف الأبصار.",
4.5, 1100, 0, True, 15, 30, ["religion", "architecture", "histoire"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?mosque,minaret,morocco", None, None)

add_lieu("lieu_010", "Arènes de Tanger (Plaza de Toros)", "monument_historique", "arenes", 35.7650, -5.8010, "Avenue des FAR, Tanger 90000, Maroc", "Ville Nouvelle",
"La Plaza de Toros de Tanger est un monument unique et inattendu, témoin silencieux de la forte influence espagnole durant l'ère de la zone internationale. Construites en 1950, ces grandes arènes pouvaient accueillir jusqu'à 13 000 spectateurs pour des spectacles de tauromachie, attirant les toreros les plus célèbres de l'époque. Bien que les corridas soient désormais abolies au Maroc et que le bâtiment soit fermé en attendant sa réhabilitation culturelle complète, son imposante structure circulaire extérieure reste impressionnante et mérite d'être photographiée pour son importance historique.",
"The Plaza de Toros in Tangier is a unique and unexpected monument, a silent witness to the strong Spanish influence during the international zone era. Built in 1950, this large bullring could hold up to 13,000 spectators for bullfighting events, attracting the most famous matadors of the time. Although bullfighting is now abolished in Morocco and the building is closed awaiting full cultural rehabilitation, its imposing circular exterior structure remains impressive and is worth photographing for its historical significance.",
"حلبة مصارعة الثيران في طنجة (بلازا دي توروس) هي معلم فريد وغير متوقع، وشاهد صامت على التأثير الإسباني القوي خلال حقبة المنطقة الدولية. بنيت هذه الحلبة الكبيرة عام 1950، وكانت تتسع لما يصل إلى 13 ألف متفرج لمشاهدة عروض مصارعة الثيران، وجذبت أشهر مصارعي الثيران في ذلك الوقت. وعلى الرغم من إلغاء مصارعة الثيران الآن في المغرب وإغلاق المبنى في انتظار إعادة تأهيله الثقافي بالكامل، إلا أن هيكله الخارجي الدائري المهيب لا يزال مثيراً للإعجاب ويستحق التصوير لأهميته التاريخية.",
3.8, 420, 0, True, 15, 30, ["histoire", "architecture", "espagnol", "insolite"], ["printemps", "automne"], True, "https://source.unsplash.com/600x400/?bullring,arena,tangier", None, None)

add_lieu("lieu_011", "Muraille de la Médina", "monument_historique", "remparts", 35.7860, -5.8110, "Pourtour de la Médina, Tanger 90000, Maroc", "Médina",
"La majestueuse muraille qui encercle l'ancienne médina de Tanger est une structure défensive redoutable datant principalement de l'occupation portugaise et de la dynastie alaouite. Longue de plusieurs kilomètres, elle est rythmée par d'imposants bastions, des tourelles de guet et des batteries de canons historiques pointées vers la mer. Suivre le chemin qui longe ces remparts massifs offre une perspective fascinante sur l'histoire militaire de la ville et permet d'admirer la transition architecturale entre la vieille ville compacte et le développement urbain moderne qui l'entoure.",
"The majestic wall encircling the old medina of Tangier is a formidable defensive structure dating primarily from the Portuguese occupation and the Alaouite dynasty. Several kilometers long, it is punctuated by imposing bastions, watchtowers, and historic cannon batteries pointed towards the sea. Following the path along these massive ramparts offers a fascinating perspective on the city's military history and allows one to admire the architectural transition between the compact old town and the modern urban development surrounding it.",
"السور المهيب الذي يحيط بمدينة طنجة القديمة هو هيكل دفاعي هائل يعود تاريخه بشكل رئيسي إلى فترة الاحتلال البرتغالي والسلالة العلوية. يمتد طوله لعدة كيلومترات، وتتخلله معاقل ضخمة وأبراج مراقبة وبطاريات مدافع تاريخية موجهة نحو البحر. إن تتبع المسار الذي يمتد على طول هذه الأسوار الضخمة يوفر منظوراً رائعاً للتاريخ العسكري للمدينة، ويسمح بالاستمتاع بالانتقال المعماري المثير بين البلدة القديمة المكتظة والتطور الحضري الحديث الذي يحيط بها من كل جانب.",
4.5, 1340, 0, True, 45, 90, ["histoire", "architecture", "remparts", "promenade"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?wall,fortress,morocco", None, None)

add_lieu("lieu_012", "Dar el Makhzen (Palais Royal)", "monument_historique", "palais", 35.7874, -5.8128, "Place de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"Dar el Makhzen, l'ancien palais royal situé au point culminant de la Kasbah, est un magnifique exemple de l'architecture résidentielle luxueuse des sultans alaouites. Construit au XVIIe siècle par le Sultan Moulay Ismaïl, ce palais somptueux s'articule autour de deux cours splendides ornées de zelliges colorés, de stucs délicats et de boiseries finement sculptées. Bien que les appartements royaux privés ne soient pas tous accessibles, le palais abrite aujourd'hui de riches collections d'artisanat et offre un aperçu inestimable du raffinement de la vie palatiale marocaine d'autrefois.",
"Dar el Makhzen, the former royal palace located at the highest point of the Kasbah, is a magnificent example of the luxurious residential architecture of the Alaouite sultans. Built in the 17th century by Sultan Moulay Ismaïl, this sumptuous palace is organized around two splendid courtyards adorned with colorful zelliges, delicate stucco work, and finely carved woodwork. Although not all private royal apartments are accessible, the palace now houses rich collections of craftsmanship and offers an invaluable glimpse into the refinement of Moroccan palatial life in the past.",
"دار المخزن، القصر الملكي السابق الواقع في أعلى نقطة بالقصبة، هو مثال رائع للهندسة المعمارية السكنية الفاخرة للسلاطين العلويين. بناه السلطان مولاي إسماعيل في القرن السابع عشر، ويتمحور هذا القصر الفخم حول فنائين رائعين مزينين بالزليج الملون والجص الرقيق والأعمال الخشبية المنحوتة بدقة بالغة. وعلى الرغم من أن جميع الشقق الملكية الخاصة ليست مفتوحة للزوار، إلا أن القصر يضم اليوم مجموعات غنية من الحرف اليدوية ويوفر لمحة لا تقدر بثمن عن مدى رقي الحياة في القصور المغربية في الماضي.",
4.6, 2100, 20, False, 60, 120, ["histoire", "architecture", "palais", "culture"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?palace,courtyard,morocco", None, None)

# 8 QUARTIERS ET MEDINAS
add_lieu("lieu_013", "Médina de Tanger", "quartier_historique", "medina", 35.7855, -5.8115, "Médina, Tanger 90000, Maroc", "Médina",
"La Médina de Tanger est une ville fortifiée ancienne, un labyrinthe vibrant de ruelles étroites, de maisons blanchies à la chaux et de portes bleues typiques de l'Andalousie. Contrairement à d'autres médinas marocaines, elle est fortement imprégnée d'influences ibériques et internationales, créant une atmosphère unique au monde. C'est le cœur battant de la ville, regorgeant d'artisans traditionnels, de boulangeries communautaires, de boutiques d'antiquités et de petits cafés cachés. S'y perdre est la meilleure façon de découvrir l'âme véritable et mystérieuse de Tanger.",
"The Medina of Tangier is an ancient walled city, a vibrant labyrinth of narrow alleys, whitewashed houses, and typical Andalusian blue doors. Unlike other Moroccan medinas, it is heavily imbued with Iberian and international influences, creating a unique atmosphere in the world. It is the beating heart of the city, brimming with traditional artisans, communal bakeries, antique shops, and hidden little cafes. Getting lost here is the absolute best way to discover the true and mysterious soul of Tangier.",
"مدينة طنجة القديمة هي مدينة مسورة قديمة، ومتاهة نابضة بالحياة من الأزقة الضيقة والمنازل المطلية باللون الأبيض والأبواب الزرقاء الأندلسية النموذجية. على عكس المدن المغربية القديمة الأخرى، فهي مشبعة بشدة بالتأثيرات الأيبيرية والدولية، مما يخلق جواً فريداً في العالم. إنها القلب النابض للمدينة، وتزخر بالحرفيين التقليديين والمخابز المجتمعية ومتاجر التحف والمقاهي الصغيرة المخفية. إن الضياع في أزقتها هو بلا شك أفضل طريقة لاكتشاف الروح الحقيقية والغامضة لمدينة طنجة العريقة.",
4.7, 5400, 0, True, 120, 240, ["quartier", "histoire", "shopping", "culture"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?medina,alley,morocco", None, None)

add_lieu("lieu_014", "Petit Socco", "quartier_historique", "place", 35.7851, -5.8112, "Souk Dakhil, Médina, Tanger 90000, Maroc", "Médina",
"Le Petit Socco (ou Souk Dakhil) est une petite place historique située au cœur battant de la médina. Autrefois le centre de la contre-culture littéraire et artistique, cet endroit mythique était le point de rendez-vous favori d'écrivains emblématiques comme Paul Bowles, William Burroughs et Jack Kerouac. Aujourd'hui, bien qu'il ait perdu une part de son aura sulfureuse d'antan, il reste l'un des lieux les plus agréables pour s'asseoir à la terrasse d'un café traditionnel, siroter un thé à la menthe et observer le ballet incessant des passants.",
"The Petit Socco (or Souk Dakhil) is a small historic square located in the beating heart of the medina. Once the center of literary and artistic counterculture, this mythical place was the favorite meeting spot for iconic writers like Paul Bowles, William Burroughs, and Jack Kerouac. Today, although it has lost some of its notorious past aura, it remains one of the most pleasant places to sit at a traditional cafe terrace, sip a sweet mint tea, and watch the endless parade of passersby.",
"السوق الصغير (أو سوق الداخل) هو ساحة تاريخية صغيرة تقع في القلب النابض للمدينة العتيقة. كان هذا المكان الأسطوري في الماضي مركزاً للثقافة المضادة الأدبية والفنية، ونقطة التقاء مفضلة للكتاب البارزين مثل بول بولز وويليام بوروز وجاك كيرواك. واليوم، على الرغم من أنه فقد جزءاً من هالته المثيرة للجدل في الماضي، إلا أنه يظل أحد أمتع الأماكن للجلوس في شرفة مقهى تقليدي، واحتساء الشاي بالنعناع المنعش، ومراقبة حركة المارة المستمرة في مشهد نابض بالحياة.",
4.3, 1850, 0, True, 30, 60, ["place", "histoire", "cafe", "culture"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?square,cafe,tangier", None, None)

add_lieu("lieu_015", "Grand Socco", "quartier_historique", "place", 35.7838, -5.8097, "Place du 9 Avril 1947, Tanger 90000, Maroc", "Centre-ville",
"Le Grand Socco (officiellement Place du 9 Avril 1947) est la place centrale la plus importante de Tanger, formant une frontière physique et symbolique entre l'ancienne médina et la ville moderne européenne. Animée jour et nuit, cette place circulaire bordée de palmiers géants, d'une belle fontaine centrale et du cinéma colonial Rif, est le point de ralliement par excellence des Tangérois. Les marchandes paysannes de la région du Rif, habillées de leurs chapeaux de paille caractéristiques, y vendent toujours leurs produits frais, préservant une tradition séculaire.",
"The Grand Socco (officially Place du 9 Avril 1947) is Tangier's most important central square, forming a physical and symbolic border between the old medina and the modern European city. Lively day and night, this circular square bordered by giant palm trees, a beautiful central fountain, and the colonial Rif cinema, is the ultimate rallying point for locals. Peasant women from the Rif region, dressed in their characteristic straw hats, still sell their fresh produce here, preserving a centuries-old tradition.",
"السوق الكبير (رسمياً ساحة 9 أبريل 1947) هو أهم ساحة مركزية في طنجة، ويشكل حدوداً مادية ورمزية بين المدينة القديمة والمدينة الأوروبية الحديثة. تعج هذه الساحة الدائرية بالحياة ليلاً ونهاراً، وهي محاطة بأشجار النخيل العملاقة، ونافورة مركزية جميلة، وسينما الريف الكولونيالية، وتعتبر نقطة التجمع بامتياز لسكان طنجة. لا تزال الفلاحات من منطقة الريف، اللواتي يرتدين قبعات القش المميزة، يبعن منتجاتهن الطازجة هنا، مما يحافظ على تقليد عريق يعود لقرون مضت.",
4.5, 3400, 0, True, 30, 60, ["place", "vie_locale", "histoire", "rencontre"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?square,fountain,morocco", None, None)

add_lieu("lieu_016", "Quartier Marshan", "quartier_historique", "quartier_residentiel", 35.7870, -5.8220, "Quartier Marshan, Tanger 90000, Maroc", "Marshan",
"Le quartier du Marshan, perché sur une falaise verdoyante à l'ouest de la Kasbah, est l'un des districts résidentiels les plus chics et paisibles de Tanger. Son histoire est riche de palais somptueux, de villas coloniales entourées de vastes jardins fleuris et de résidences diplomatiques. C'est ici que se trouvent des lieux emblématiques comme le Palais du Mendoub et le légendaire Café Hafa. Se promener dans les rues calmes bordées de bougainvilliers du Marshan offre une expérience relaxante et des vues splendides, loin du bruit intense du centre-ville.",
"The Marshan district, perched on a lush cliff west of the Kasbah, is one of Tangier's most chic and peaceful residential areas. Its history is rich with sumptuous palaces, colonial villas surrounded by vast flowering gardens, and diplomatic residences. This is where iconic places like the Mendoub Palace and the legendary Café Hafa are located. Strolling through Marshan's quiet bougainvillea-lined streets offers a relaxing experience and splendid views, far away from the intense noise of the bustling city center.",
"حي المرشان، الجاثم على جرف أخضر غرب القصبة، هو واحد من أرقى وأهدأ الأحياء السكنية في طنجة. يزخر تاريخه بالقصور الفخمة، والفيلات الاستعمارية المحاطة بحدائق شاسعة مليئة بالزهور، والمساكن الدبلوماسية. هنا توجد أماكن أيقونية مثل قصر المندوب ومقهى الحافة الأسطوري. إن التجول في شوارع المرشان الهادئة المليئة بأشجار الجهنمية يوفر تجربة مريحة وإطلالات رائعة، بعيداً عن الضوضاء الشديدة وصخب وسط المدينة، مما يجعله ملاذاً مثالياً للاسترخاء.",
4.4, 800, 0, True, 60, 120, ["quartier", "promenade", "architecture", "calme"], ["printemps", "automne"], True, "https://source.unsplash.com/600x400/?residential,street,tangier", None, None)

add_lieu("lieu_017", "Quartier Iberia (Espagnol)", "quartier_historique", "quartier_moderne", 35.7760, -5.8110, "Place Iberia, Tanger 90000, Maroc", "Centre-ville",
"Le quartier Iberia est un témoin remarquable de l'architecture moderne et fonctionnaliste espagnole des années 1940 et 1950. Établi autour de l'élégante place du même nom et de la cathédrale espagnole, ce quartier planifié contraste fortement avec la médina par ses larges avenues, ses bâtiments aux façades symétriques et balcons filants, et ses institutions culturelles comme l'Institut Cervantès. C'est une zone résidentielle et administrative aisée, idéale pour découvrir l'héritage architectural européen massif laissé lors de la période internationale, tout en profitant de cafés branchés.",
"The Iberia district is a remarkable witness to modern and functionalist Spanish architecture from the 1940s and 1950s. Established around the elegant square of the same name and the Spanish cathedral, this planned neighborhood contrasts sharply with the medina with its wide avenues, symmetrical buildings with continuous balconies, and cultural institutions like the Cervantes Institute. It is an affluent residential and administrative area, ideal for discovering the massive European architectural heritage left during the international period, while enjoying trendy cafes.",
"حي إيبيريا هو شاهد رائع على العمارة الإسبانية الحديثة والوظيفية في الأربعينيات والخمسينيات. تم إنشاء هذا الحي المخطط حول الساحة الأنيقة التي تحمل الاسم نفسه والكاتدرائية الإسبانية، وهو يتناقض بشدة مع المدينة القديمة بشوارعه الواسعة ومبانيه ذات الواجهات المتناظرة والشرفات المتصلة، والمؤسسات الثقافية مثل معهد سرفانتس. إنها منطقة سكنية وإدارية راقية، ومثالية لاكتشاف التراث المعماري الأوروبي الضخم الذي ترك خلال الفترة الدولية، مع الاستمتاع بزيارة المقاهي العصرية.",
4.2, 500, 0, True, 45, 90, ["architecture", "quartier", "espagnol", "moderne"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?architecture,avenue,morocco", None, None)

add_lieu("lieu_018", "Quartier Californie", "quartier_historique", "quartier_residentiel", 35.7650, -5.8400, "Quartier Californie, Tanger 90000, Maroc", "Californie",
"Nommé d'après l'État américain en raison de ses collines ensoleillées, de ses villas luxueuses et de son abondance de palmiers, le quartier Californie est l'enclave résidentielle la plus huppée de Tanger. Dominant la ville et entouré de pinèdes odorantes, il abrite certaines des propriétés les plus prestigieuses du Maroc, y compris des résidences royales du Golfe. Bien qu'il n'y ait pas de monuments touristiques spécifiques à visiter, une promenade en voiture à travers ses larges rues sinueuses permet d'admirer une architecture contemporaine grandiose et de superbes panoramas sur la mer.",
"Named after the American state due to its sunny hills, luxurious villas, and abundance of palm trees, the Californie district is Tangier's most upscale residential enclave. Overlooking the city and surrounded by fragrant pine forests, it houses some of Morocco's most prestigious properties, including Gulf royal residences. While there are no specific tourist monuments to visit, a drive through its wide, winding streets allows one to admire grandiose contemporary architecture and stunning panoramic views of the sea.",
"سمي هذا الحي باسم الولاية الأمريكية بسبب تلاله المشمسة وفيلاته الفاخرة ووفرة أشجار النخيل فيه، وهو الجيب السكني الأكثر رقياً في طنجة. يطل على المدينة وتحيط به غابات الصنوبر العطرة، ويضم بعضاً من أرقى العقارات في المغرب، بما في ذلك المساكن الملكية الخليجية. على الرغم من عدم وجود معالم سياحية محددة يمكن زيارتها، إلا أن القيادة عبر شوارعها الواسعة والمتعرجة تتيح للمرء الاستمتاع بالهندسة المعمارية المعاصرة الرائعة والإطلالات البانورامية المذهلة على البحر.",
3.9, 210, 0, True, 30, 60, ["quartier", "luxe", "architecture", "panorama"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?mansion,luxury,hill", None, None)

add_lieu("lieu_019", "Malabata", "quartier_historique", "corniche", 35.7940, -5.7840, "Baie de Tanger Est, Tanger 90000, Maroc", "Malabata",
"S'étendant sur la baie orientale de la ville, Malabata est le quartier balnéaire et moderne par excellence de Tanger. Avec ses hôtels de luxe cinq étoiles, ses casinos scintillants, sa longue corniche aménagée idéale pour le jogging ou la promenade nocturne, et sa nouvelle marina étincelante, le quartier représente le visage contemporain et dynamique du Maroc. Au bout du cap Malabata, un phare pittoresque veille sur le détroit, offrant un point de vue exceptionnel pour contempler l'ensemble de la baie de Tanger d'un côté, et les côtes espagnoles de l'autre.",
"Stretching along the eastern bay of the city, Malabata is Tangier's ultimate modern seaside district. With its five-star luxury hotels, glittering casinos, long landscaped corniche perfect for jogging or evening strolls, and its sparkling new marina, the neighborhood represents the contemporary and dynamic face of Morocco. At the tip of Cape Malabata, a picturesque lighthouse watches over the strait, offering an exceptional viewpoint to contemplate the entire bay of Tangier on one side, and the Spanish coasts on the other.",
"تمتد ملاباطا على الخليج الشرقي للمدينة، وهي الحي الساحلي والحديث بامتياز في طنجة. بفضل فنادقها الفاخرة ذات الخمس نجوم، وكازينوهاتها المتلألئة، وكورنيشها الطويل ذو المناظر الطبيعية المثالية للركض أو التنزه ليلاً، والمارينا الجديدة المتلألئة، يمثل الحي الوجه المعاصر والديناميكي للمغرب. في نهاية رأس ملاباطا، تحرس منارة خلابة المضيق، وتوفر نقطة مشاهدة استثنائية للتأمل في خليج طنجة بأكمله من جهة، والسواحل الإسبانية من جهة أخرى في مشهد مذهل.",
4.5, 2700, 0, True, 60, 180, ["plage", "moderne", "promenade", "corniche"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?corniche,beach,tangier", None, None)

add_lieu("lieu_020", "Quartier de la Kasbah", "quartier_historique", "quartier_fortifie", 35.7875, -5.8130, "Kasbah, Tanger 90000, Maroc", "Kasbah",
"Le quartier fortifié de la Kasbah, bien distinct de la médina en contrebas, est un secteur résidentiel fascinant où chaque mur semble imprégné d'histoire. Historiquement le centre du pouvoir, le quartier est organisé autour de la place de la Kasbah et abrite de magnifiques riads transformés en maisons d'hôtes de charme, des restaurants gastronomiques et des galeries d'art intimistes. Ses murs immaculés peints à la chaux, ses lourdes portes en bois sculpté et son calme relatif comparé au souk en font l'un des lieux de promenade les plus romantiques du Nord du Maroc.",
"The fortified district of the Kasbah, quite distinct from the medina below, is a fascinating residential area where every wall seems steeped in history. Historically the center of power, the neighborhood is organized around Kasbah Square and houses magnificent riads converted into charming guesthouses, gourmet restaurants, and intimate art galleries. Its pristine whitewashed walls, heavy carved wooden doors, and relative calm compared to the souk make it one of the most romantic places to stroll in Northern Morocco.",
"يعد حي القصبة المحصن، المتميز بوضوح عن المدينة القديمة أدناه، منطقة سكنية رائعة حيث يبدو كل جدار فيها مشبعاً بعبق التاريخ. كان الحي تاريخياً مركزاً للسلطة، وينتظم حول ساحة القصبة ويضم رياضات رائعة تم تحويلها إلى دور ضيافة ساحرة، ومطاعم ذواقة راقية، ومعارض فنية حميمة. جدرانها البيضاء الناصعة، وأبوابها الخشبية المنحوتة الثقيلة، وهدوؤها النسبي مقارنة بالسوق تجعلها واحدة من أكثر الأماكن رومانسية للتنزه في شمال المغرب.",
4.7, 3100, 0, True, 60, 150, ["kasbah", "romantique", "histoire", "calme"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?kasbah,alley,morocco", None, None)

with open(r'c:\Users\HP\Documents\projet touristique\dataset\lieux_touristiques.json', 'w', encoding='utf-8') as f:
    json.dump(lieux, f, ensure_ascii=False, indent=2)
print(f'Part 1: {len(lieux)} lieux generated')
