import json
import os

filepath_part1 = r'c:\Users\HP\Documents\projet touristique\dataset\faq_part1.json'

with open(filepath_part1, 'r', encoding='utf-8') as f:
    faqs = json.load(f)

def add(cat,intent,qf,qe,qa,rf,re,ra,tags,pri):
    faqs.append({"id":f"faq_{len(faqs)+1:03d}","categorie":cat,"intention":intent,"question_fr":qf,"question_en":qe,"question_ar":qa,"reponse_fr":rf,"reponse_en":re,"reponse_ar":ra,"tags":tags,"priorite":pri})

# HOTELS (6)
add("hotels","hotel_luxe","Quels sont les meilleurs hôtels 5 étoiles ?","What are the best 5-star hotels?","ما هي أفضل الفنادق 5 نجوم؟","El Minzah (historique), Fairmont Tazi Palace, Hilton City Center, Sofitel Malabata, Nord-Pinus (boutique).","El Minzah (historic), Fairmont Tazi Palace, Hilton City Center, Sofitel Malabata, Nord-Pinus (boutique).","المنزه (تاريخي)، فيرمونت قصر التازي، هيلتون سيتي سنتر، سوفيتيل ملاباطا، نور-بينوس.",["luxe","hotel","5_etoiles"],1)
add("hotels","riad_medina","Pouvez-vous recommander un riad dans la médina ?","Can you recommend a riad in the medina?","هل يمكنك التوصية برياض في المدينة القديمة؟","Dar Chams Tanja, La Tangerina, Dar Sultan et Riad Andaluz offrent une expérience traditionnelle excellente au cœur de la Kasbah/Médina.","Dar Chams Tanja, La Tangerina, Dar Sultan and Riad Andaluz offer an excellent traditional experience in the Kasbah/Medina.","دار شمس طنجة، لا طنجرينا، دار السلطان ورياض الأندلس تقدم تجربة تقليدية ممتازة.",["riad","medina","traditionnel"],1)
add("hotels","hotel_budget","Où loger avec un petit budget ?","Where to stay on a tight budget?","أين أقيم بميزانية محدودة؟","L'Auberge de Jeunesse (dortoirs à 80 MAD), Hôtel Magellan, ou Ibis City Center offrent un bon rapport qualité-prix en centre-ville.","Youth Hostel (dorms at 80 MAD), Hotel Magellan, or Ibis City Center offer good value in the city center.","نزل الشباب (غرف مشتركة بـ80 درهم)، فندق ماجلان، أو إيبس سيتي سنتر توفر قيمة جيدة.",["budget","economique","auberge"],1)
add("hotels","hotel_vue_mer","Quels hôtels ont une vue sur la mer ?","Which hotels have a sea view?","ما الفنادق التي تطل على البحر؟","Sofitel Malabata, Barcelo Tanger, El Oumnia Puerto (sur la corniche) et les riads de la Kasbah comme Dar Nour.","Sofitel Malabata, Barcelo Tanger, El Oumnia Puerto (on the corniche) and Kasbah riads like Dar Nour.","سوفيتيل ملاباطا، بارسيلو طنجة، الأمنية بويرتو (على الكورنيش) ورياضات القصبة مثل دار النور.",["vue_mer","hotel","plage"],2)
add("hotels","hotel_famille","Quels sont les meilleurs hôtels pour les familles ?","What are the best hotels for families?","ما هي أفضل الفنادق للعائلات؟","Movenpick, Hilton et Sofitel disposent de grandes piscines, chambres familiales et parfois de clubs enfants.","Movenpick, Hilton and Sofitel have large pools, family rooms and sometimes kids clubs.","موفنبيك، هيلتون وسوفيتيل تحتوي على مسابح كبيرة، غرف عائلية وأحياناً نوادي للأطفال.",["famille","piscine","hotel"],2)
add("hotels","taxe_sejour","Y a-t-il une taxe de séjour à payer ?","Is there a tourist tax to pay?","هل هناك ضريبة سياحية يجب دفعها؟","Oui, une taxe de promotion touristique (de 10 à 40 MAD par personne et par nuit selon la catégorie de l'hôtel) s'applique.","Yes, a tourist promotion tax (10 to 40 MAD per person per night depending on hotel category) applies.","نعم، تطبق ضريبة الإنعاش السياحي (من 10 إلى 40 درهم للشخص في الليلة حسب فئة الفندق).",["taxe","budget","pratique"],3)

# URGENCES (6)
add("urgences","numero_police","Quel est le numéro de la police ?","What is the police number?","ما هو رقم الشرطة؟","Composez le 19 pour la police urbaine (Sûreté Nationale) ou le 177 pour la Gendarmerie Royale (hors agglomération).","Dial 19 for urban police (National Security) or 177 for Royal Gendarmerie (outside town).","اتصل بالرقم 19 لشرطة المدينة أو 177 للدرك الملكي (خارج المدار الحضري).",["police","urgence","securite"],1)
add("urgences","numero_pompier","Quel est le numéro des pompiers et urgences médicales ?","What is the number for fire and medical emergencies?","ما هو رقم المطافئ والطوارئ الطبية؟","Composez le 15 pour la Protection Civile (pompiers et ambulances d'urgence).","Dial 15 for Civil Protection (fire brigade and emergency ambulances).","اتصل بالرقم 15 للوقاية المدنية (المطافئ وسيارات الإسعاف).",["pompier","ambulance","urgence"],1)
add("urgences","hopital_recommande","Quel hôpital ou clinique recommandez-vous en cas d'urgence ?","Which hospital or clinic do you recommend in an emergency?","أي مستشفى أو عيادة تنصح بها في حالة الطوارئ؟","La Clinique Al Amal et l'Hôpital Duc de Tovar (Espagnol) sont très recommandés pour les étrangers. Urgences 24h/24.","Clinique Al Amal and Duc de Tovar (Spanish) Hospital are highly recommended for foreigners. 24/7 emergencies.","ينصح بشدة بعيادة الأمل ومستشفى دوق دي توفار (الإسباني) للأجانب. طوارئ 24/24.",["hopital","clinique","sante"],1)
add("urgences","pharmacie_garde","Comment trouver une pharmacie de garde la nuit ?","How to find an on-duty pharmacy at night?","كيف أجد صيدلية مناوبة ليلاً؟","Les pharmacies Pasteur, Rif et Ibn Sina assurent souvent les gardes. La liste est affichée sur la porte de toutes les pharmacies.","Pasteur, Rif and Ibn Sina pharmacies are often on duty. The list is posted on the door of all pharmacies.","صيدليات باستور، الريف وابن سينا غالباً ما تكون مناوبة. القائمة معلقة على باب جميع الصيدليات.",["pharmacie","nuit","sante"],1)
add("urgences","perte_passeport","Que faire en cas de perte de passeport ?","What to do if I lose my passport?","ماذا أفعل في حالة فقدان جواز السفر؟","Faites une déclaration de perte au Commissariat Central, puis contactez votre consulat (France, Espagne, etc.) à Tanger pour un laissez-passer.","Report the loss at the Central Police Station, then contact your consulate (France, Spain, etc.) in Tangier for a laissez-passer.","قم بتقديم تصريح بالضياع في المفوضية المركزية، ثم اتصل بقنصليتك في طنجة للحصول على تصريح مرور.",["passeport","perte","consulat"],2)
add("urgences","eau_potable","L'eau du robinet est-elle potable ?","Is tap water safe to drink?","هل ماء الصنبور صالح للشرب؟","L'eau est traitée et potable, mais il est recommandé aux touristes de boire de l'eau en bouteille (Sidi Ali, Sidi Harazem) pour éviter les maux de ventre.","Water is treated and safe, but tourists are advised to drink bottled water to avoid stomach upsets.","الماء معالج وصالح للشرب، لكن ينصح السياح بشرب المياه المعبأة لتجنب آلام المعدة.",["eau","sante","pratique"],3)

# CULTURE (8)
add("culture","langues_parlees","Quelles langues parle-t-on à Tanger ?","What languages are spoken in Tangier?","ما اللغات المتحدث بها في طنجة؟","L'arabe marocain (darija) et l'espagnol sont très répandus. Le français est courant, et l'anglais est de plus en plus parlé dans les zones touristiques.","Moroccan Arabic (darija) and Spanish are widely spoken. French is common, and English is increasingly spoken in tourist areas.","الدارجة المغربية والإسبانية منتشرتان جداً. الفرنسية شائعة، والإنجليزية تتحدث بشكل متزايد في المناطق السياحية.",["langue","communication","pratique"],1)
add("culture","tenue_vestimentaire","Comment s'habiller à Tanger ?","How to dress in Tangier?","كيف أرتدي ملابسي في طنجة؟","Tenue décontractée acceptée, mais il est respectueux de couvrir épaules et genoux, surtout dans la médina. Maillots de bain réservés aux plages/piscines.","Casual dress accepted, but it is respectful to cover shoulders and knees, especially in the medina. Swimwear reserved for beaches/pools.","لباس غير رسمي مقبول، لكن من الاحترام تغطية الكتفين والركبتين، خاصة في المدينة. ملابس السباحة مخصصة للشواطئ/المسابح.",["tenue","coutumes","respect"],1)
add("culture","pourboire_pratique","Doit-on laisser un pourboire ?","Should I leave a tip?","هل يجب ترك بقشيش؟","Oui, le pourboire (5-10%) est apprécié dans les restaurants, pour les guides, et les porteurs (10-20 MAD). Laissez 2-5 MAD dans les petits cafés.","Yes, tipping (5-10%) is appreciated in restaurants, for guides, and porters (10-20 MAD). Leave 2-5 MAD in small cafes.","نعم، البقشيش (5-10%) مقدر في المطاعم، وللمرشدين، والحمالين (10-20 درهم). اترك 2-5 دراهم في المقاهي الصغيرة.",["pourboire","argent","coutumes"],1)
add("culture","festivals_tanger","Quels sont les principaux festivals ?","What are the main festivals?","ما هي المهرجانات الرئيسية؟","Tanjazz (septembre), Festival National du Film (février/mars), et le Moussem culturel d'Asilah en été (à proximité).","Tanjazz (September), National Film Festival (February/March), and Asilah Cultural Moussem in summer (nearby).","طنجاز (سبتمبر)، المهرجان الوطني للفيلم (فبراير/مارس)، وموسم أصيلة الثقافي في الصيف (بالقرب).",["festival","musique","evenement"],2)
add("culture","achat_artisanat","Quel artisanat acheter à Tanger ?","What crafts to buy in Tangier?","ما هي الحرف اليدوية التي يمكن شراؤها في طنجة؟","Cuir, tapis, céramique du Rif, lampes en laiton, huile d'argan, épices, et les fameux chapeaux de paille (taraza) à pompons du Nord.","Leather, rugs, Rif ceramics, brass lamps, argan oil, spices, and the famous northern pom-pom straw hats (taraza).","الجلد، السجاد، خزف الريف، المصابيح النحاسية، زيت الأركان، التوابل، وقبعات القش الشهيرة بكريات الصوف في الشمال.",["artisanat","souvenir","shopping"],2)
add("culture","marchandage_souk","Faut-il marchander dans les souks ?","Do you have to haggle in the souks?","هل يجب المساومة في الأسواق؟","Oui, le marchandage est une tradition. Proposez d'abord 30-40% du prix initial demandé et négociez avec le sourire.","Yes, haggling is a tradition. Start by offering 30-40% of the initial asking price and negotiate with a smile.","نعم، المساومة تقليد. اقترح أولاً 30-40٪ من السعر المطلوب الأولي وتفاوض بابتسامة.",["marchandage","souk","shopping"],2)
add("culture","vendredi_prieres","Que se passe-t-il le vendredi ?","What happens on Fridays?","ماذا يحدث يوم الجمعة؟","Le vendredi est jour de prière. Beaucoup de commerces de la médina ferment entre 12h et 15h. C'est le jour traditionnel du couscous.","Friday is prayer day. Many medina shops close between 12pm and 3pm. It's the traditional day for couscous.","الجمعة يوم الصلاة. تغلق العديد من متاجر المدينة بين 12 و 15 زوالاً. إنه اليوم التقليدي للكسكس.",["vendredi","religion","coutumes"],3)
add("culture","photographie_locaux","Peut-on photographier les habitants ?","Can you photograph the locals?","هل يمكن تصوير السكان المحليين؟","Demandez toujours la permission avant de photographier quelqu'un, particulièrement les femmes et les personnes âgées dans la médina.","Always ask permission before photographing someone, especially women and the elderly in the medina.","اطلب الإذن دائماً قبل تصوير أي شخص، خاصة النساء وكبار السن في المدينة القديمة.",["photographie","respect","coutumes"],3)

# METEO (4)
add("meteo","meilleure_saison","Quelle est la meilleure saison pour visiter ?","What is the best season to visit?","ما هو أفضل فصل للزيارة؟","Le printemps (avril-juin) et l'automne (septembre-octobre) offrent un climat doux. L'été est idéal pour les plages mais très fréquenté.","Spring (April-June) and autumn (September-October) offer mild weather. Summer is ideal for beaches but very crowded.","الربيع (أبريل-يونيو) والخريف (سبتمبر-أكتوبر) يوفران مناخاً معتدلاً. الصيف مثالي للشواطئ لكنه مزدحم جداً.",["saison","climat","visite"],1)
add("meteo","meteo_hiver","Fait-il froid en hiver ?","Is it cold in winter?","هل الجو بارد في الشتاء؟","Les hivers (décembre-février) sont doux (10-16°C) mais souvent pluvieux et venteux à cause de la proximité du détroit et de l'océan.","Winters (December-February) are mild (10-16°C) but often rainy and windy due to the proximity of the strait and ocean.","الشتاء (ديسمبر-فبراير) معتدل (10-16 درجة مئوية) ولكنه غالباً ممطر وعاصف بسبب القرب من المضيق والمحيط.",["hiver","climat","pluie"],2)
add("meteo","vent_chergui","Qu'est-ce que le Chergui ?","What is the Chergui?","ما هو الشرقي؟","Le Chergui est un vent d'est sec et chaud qui souffle parfois sur Tanger, particulièrement en été, rendant l'air très sec.","The Chergui is a dry and hot east wind that sometimes blows over Tangier, especially in summer, making the air very dry.","الشرقي هو ريح شرقية جافة وحارة تهب أحياناً على طنجة، خاصة في الصيف، مما يجعل الهواء جافاً جداً.",["vent","chergui","climat"],3)
add("meteo","baignade_saison","Quand peut-on se baigner ?","When can you swim?","متى يمكن السباحة؟","L'eau de mer est assez fraîche. La meilleure période pour la baignade s'étend de fin juin à septembre (eau entre 20 et 24°C).","The sea water is quite cool. The best time for swimming is from late June to September (water between 20 and 24°C).","مياه البحر باردة نسبياً. أفضل فترة للسباحة تمتد من أواخر يونيو إلى سبتمبر (الماء بين 20 و 24 درجة مئوية).",["baignade","mer","ete"],3)

# MONNAIE (4)
add("monnaie","devise_marocaine","Quelle est la monnaie locale ?","What is the local currency?","ما هي العملة المحلية؟","La monnaie est le Dirham Marocain (MAD). 1 Euro = environ 10,8 MAD. 1 USD = environ 10 MAD.","The currency is the Moroccan Dirham (MAD). 1 Euro = approx 10.8 MAD. 1 USD = approx 10 MAD.","العملة هي الدرهم المغربي. 1 يورو = حوالي 10.8 درهم. 1 دولار = حوالي 10 دراهم.",["monnaie","dirham","argent"],1)
add("monnaie","bureau_change","Où changer de l'argent ?","Where to change money?","أين أصرف الأموال؟","Dans les banques ou bureaux de change officiels du centre-ville (Boulevard Pasteur). Évitez le change à l'aéroport (taux moins avantageux) ou dans la rue.","In banks or official exchange offices in the city center (Boulevard Pasteur). Avoid airport exchange (worse rates) or street exchange.","في البنوك أو مكاتب الصرف الرسمية في وسط المدينة (شارع باستور). تجنب الصرف في المطار أو في الشارع.",["change","argent","banque"],1)
add("monnaie","carte_bancaire","Peut-on payer par carte bancaire ?","Can you pay by credit card?","هل يمكن الدفع بالبطاقة البنكية؟","Oui, dans les hôtels, grands restaurants et magasins modernes. Mais ayez toujours de l'espèce pour les taxis, les petits commerces et la médina.","Yes, in hotels, large restaurants and modern shops. But always have cash for taxis, small shops and the medina.","نعم، في الفنادق والمطاعم الكبيرة والمتاجر الحديثة. لكن احتفظ دائماً بالنقود لسيارات الأجرة والمتاجر الصغيرة والمدينة.",["carte","paiement","argent"],1)
add("monnaie","distributeur_billet","Trouve-t-on facilement des distributeurs (GAB) ?","Are ATMs easy to find?","هل يسهل العثور على أجهزة الصراف الآلي؟","Oui, de nombreux distributeurs sont disponibles en ville (Attijariwafa, BMCE, Banque Populaire). Certains prennent une commission fixe par retrait.","Yes, many ATMs are available in town (Attijariwafa, BMCE, Banque Populaire). Some charge a fixed fee per withdrawal.","نعم، تتوفر العديد من أجهزة الصراف الآلي في المدينة. بعضها يأخذ عمولة ثابتة لكل عملية سحب.",["gab","retrait","banque"],2)

with open(r'c:\Users\HP\Documents\projet touristique\dataset\faq_chatbot.json','w',encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)

print(f"Total FAQs générées : {len(faqs)}")
