import json
import os

with open(r'c:\Users\HP\Documents\projet touristique\dataset\lieux_touristiques.json', 'r', encoding='utf-8') as f:
    lieux = json.load(f)

def add_lieu(id_val, nom, cat, scat, lat, lon, adr, qrt, d_fr, d_en, d_ar, note, avis, prix, gratuit, duree_min, duree_max, tags, saison, pmr, img, web, tel):
    lieux.append({
        "id": id_val, "nom": nom, "categorie": cat, "sous_categorie": scat,
        "latitude": lat, "longitude": lon, "adresse": adr, "quartier": qrt,
        "description_fr": d_fr, "description_en": d_en, "description_ar": d_ar,
        "note_moyenne": note, "nb_avis": avis, "prix_entree_mad": prix, "gratuit": gratuit,
        "horaires": {
            "lundi": "09:00-18:00", "mardi": "09:00-18:00", "mercredi": "09:00-18:00",
            "jeudi": "09:00-18:00", "vendredi": "09:00-18:00", "samedi": "09:00-20:00", "dimanche": "09:00-20:00"
        },
        "duree_visite_min": duree_min, "duree_visite_max": duree_max,
        "tags": tags, "saison_recommandee": saison, "accessibilite_pmr": pmr,
        "image_url": img, "site_web": web, "telephone": tel, "source_donnee": "Google Places + OpenStreetMap"
    })

# 6 VIEWPOINTS ET PANORAMAS
add_lieu("lieu_021", "Terrasse des Paresseux", "viewpoint", "panorama", 35.7820, -5.8115, "Boulevard Pasteur, Tanger 90000, Maroc", "Centre-ville",
"La Terrasse des Paresseux est sans doute le belvédère le plus célèbre du centre-ville de Tanger. Offrant une vue dégagée, spectaculaire et ininterrompue sur le port grouillant d'activité, la baie azur de Tanger et, par temps clair, les côtes lointaines de l'Espagne et le rocher de Gibraltar. Bordée d'anciens canons en bronze qui pointent symboliquement vers l'Europe, elle tire son nom affectueux des nombreux Tangérois et touristes qui viennent s'y accouder des heures durant, en toute nonchalance, simplement pour observer le lent passage des énormes navires traversant le détroit.",
"The Terrace of the Lazy (Terrasse des Paresseux) is arguably the most famous viewpoint in downtown Tangier. It offers a clear, spectacular, and uninterrupted view of the bustling port, the azure bay of Tangier, and on clear days, the distant coasts of Spain and the Rock of Gibraltar. Lined with ancient bronze cannons pointing symbolically towards Europe, it derives its affectionate name from the many locals and tourists who come to lean on its walls for hours, in utter nonchalance, simply watching the slow passage of massive ships crossing the strait.",
"تعد مصطبة الكسالى (تراس دي بارييسو) بلا شك أشهر نقطة مشاهدة في وسط مدينة طنجة. توفر إطلالة واضحة ومذهلة وغير منقطعة على الميناء الصاخب، وخليج طنجة اللازوردي، وفي الأيام الصافية، السواحل البعيدة لإسبانيا وصخرة جبل طارق. تصطف على طولها مدافع برونزية قديمة تشير رمزياً نحو أوروبا، وتستمد اسمها المحبب من العديد من السكان المحليين والسياح الذين يأتون للاستناد على جدرانها لساعات طويلة، بكل لا مبالاة وهدوء، لمجرد مشاهدة المرور البطيء للسفن الضخمة التي تعبر المضيق باستمرار.",
4.6, 2150, 0, True, 15, 45, ["panorama", "mer", "centre_ville", "gratuit"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?viewpoint,ocean,tangier", None, None)

add_lieu("lieu_022", "Belvédère de la Kasbah", "viewpoint", "panorama", 35.7885, -5.8122, "Place de la Kasbah, Tanger 90000, Maroc", "Kasbah",
"Le Belvédère de la Kasbah, situé juste à la sortie de la célèbre porte Bab Bhar (Porte de la Mer), offre ce qui est souvent considéré comme la vue la plus romantique et emblématique de Tanger. Depuis cet escarpement rocheux situé en hauteur, le regard plonge directement sur l'ancienne médina qui dévale en cascades de toits blancs vers le port et l'océan scintillant. C'est le spot de prédilection des photographes au lever du soleil, lorsque la lumière dorée matinale baigne la ville, révélant la beauté intemporelle de la perle du Nord.",
"The Kasbah Belvedere, located right outside the famous Bab Bhar (Gate of the Sea), offers what is often considered the most romantic and iconic view of Tangier. From this high rocky escarpment, your gaze plunges directly onto the old medina cascading in a waterfall of white roofs towards the port and the sparkling ocean. It is the favorite spot for photographers at sunrise, when the golden morning light bathes the city, revealing the timeless beauty of the pearl of the North in all its splendor.",
"يوفر مرقب القصبة، الواقع خارج باب البحر الشهير مباشرة، ما يعتبر غالباً المشهد الأكثر رومانسية وأيقونية في طنجة. من هذا الجرف الصخري المرتفع، تنحدر نظرتك مباشرة إلى المدينة القديمة التي تتدرج كشلال من الأسطح البيضاء نحو الميناء والمحيط المتلألئ. إنه المكان المفضل للمصورين عند شروق الشمس، عندما يغمر ضوء الصباح الذهبي المدينة بأكملها، كاشفاً عن الجمال الخالد لجوهرة الشمال بكل روعتها وسحرها الذي لا يُقاوم.",
4.8, 1450, 0, True, 15, 30, ["panorama", "kasbah", "photographie", "mer"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?belvedere,kasbah,morocco", None, None)

add_lieu("lieu_023", "Colline du Charf", "viewpoint", "colline", 35.7610, -5.7950, "Colline de Charf, Tanger 90000, Maroc", "Charf",
"La Colline du Charf est un promontoire naturel méconnu de la plupart des touristes, mais qui offre un panorama absolument exceptionnel à 360 degrés sur l'ensemble de la région tangéroise. D'un côté, on domine la ville entière, la baie étincelante et le port moderne ; de l'autre, le regard embrasse les vertes collines environnantes et les plaines agricoles qui s'étendent vers l'intérieur du pays. C'est un endroit d'une tranquillité absolue, idéal au crépuscule pour échapper à la foule et contempler la topographie spectaculaire qui fait le charme unique de Tanger.",
"The Charf Hill is a natural promontory unknown to most tourists, but which offers an absolutely exceptional 360-degree panorama of the entire Tangier region. On one side, you overlook the whole city, the sparkling bay, and the modern port; on the other, the view embraces the surrounding green hills and agricultural plains stretching inland. It is a place of absolute tranquility, ideal at dusk to escape the crowds and contemplate the spectacular topography that gives Tangier its unique and captivating charm.",
"تلة الشرف هي نتوء طبيعي غير معروف لمعظم السياح، ولكنها توفر بانوراما استثنائية بزاوية 360 درجة لمنطقة طنجة بأكملها. من جهة، تطل على المدينة بأكملها والخليج المتلألئ والميناء الحديث؛ ومن جهة أخرى، يعانق المنظر التلال الخضراء المحيطة والسهول الزراعية الممتدة نحو الداخل. إنه مكان يتميز بالهدوء المطلق، وهو مثالي عند الغسق للهروب من الزحام والتأمل في الطبوغرافيا المذهلة التي تمنح طنجة سحرها الفريد والآسر الذي لا ينسى.",
4.3, 210, 0, True, 20, 60, ["panorama", "colline", "nature", "tranquillite"], ["printemps", "ete"], False, "https://source.unsplash.com/600x400/?hill,panorama,morocco", None, None)

add_lieu("lieu_024", "Terrasse du Café Hafa", "viewpoint", "cafe_historique", 35.7915, -5.8235, "Rue Hafa, Tanger 90000, Maroc", "Marshan",
"Fondé en 1921, le Café Hafa est bien plus qu'un simple café : c'est un point de vue institutionnel et mythique de Tanger. Ses terrasses en escalier s'accrochent de façon spectaculaire à la falaise abrupte de Marshan, offrant une vue plongeante hypnotique sur les eaux bleues du détroit de Gibraltar et les côtes andalouses si proches. Fréquenté par des légendes comme les Rolling Stones, Sean Connery et d'innombrables écrivains, ce lieu rustique et hors du temps est incontournable pour savourer le meilleur thé à la menthe de la ville tout en regardant le coucher du soleil.",
"Founded in 1921, Café Hafa is much more than just a café: it is an institutional and mythical viewpoint of Tangier. Its terraced steps cling spectacularly to the steep cliff of Marshan, offering a hypnotic plunging view over the blue waters of the Strait of Gibraltar and the incredibly close Andalusian coasts. Frequented by legends like the Rolling Stones, Sean Connery, and countless writers, this rustic and timeless place is a must-visit to savor the best mint tea in the city while watching the sunset.",
"تأسس مقهى الحافة عام 1921، وهو أكثر بكثير من مجرد مقهى: إنه نقطة مشاهدة مؤسسية وأسطورية في طنجة. تتشبث مدرجاته بشكل مذهل بجرف المرشان الحاد، مما يوفر إطلالة ساحرة ومباشرة على المياه الزرقاء لمضيق جبل طارق والسواحل الأندلسية القريبة جداً. هذا المكان الريفي والخالد، الذي ارتاده أساطير مثل رولينج ستونز وشون كونري وعدد لا يحصى من الكتاب، هو محطة لا بد منها لتذوق أفضل شاي بالنعناع في المدينة مع مشاهدة غروب الشمس المذهل.",
4.7, 5100, 0, True, 60, 120, ["cafe", "panorama", "histoire", "coucher_soleil"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?cafe,view,tangier", None, None)

add_lieu("lieu_025", "Point de vue du Cap Spartel", "viewpoint", "falaise", 35.7910, -5.9260, "Route du Cap Spartel, Tanger 90000, Maroc", "Cap Spartel",
"En contrebas du célèbre phare, la route côtière du Cap Spartel serpente au sommet d'immenses falaises verdoyantes plongeant vertigineusement dans l'océan sauvage. De nombreux petits belvédères naturels aménagés le long de la route offrent des vues époustouflantes sur la rencontre majestueuse entre les vagues puissantes de l'océan Atlantique et les eaux plus calmes de la mer Méditerranée. C'est l'un des meilleurs endroits de la région pour photographier la faune marine, les oiseaux migrateurs, et surtout, pour assister à l'un des couchers de soleil les plus grandioses d'Afrique du Nord.",
"Below the famous lighthouse, the Cape Spartel coastal road winds atop immense green cliffs plunging vertiginously into the wild ocean. Numerous small natural viewpoints arranged along the road offer breathtaking views of the majestic meeting between the powerful waves of the Atlantic Ocean and the calmer waters of the Mediterranean Sea. It is one of the best places in the region to photograph marine wildlife, migratory birds, and above all, to witness one of the most magnificent sunsets in all of North Africa.",
"أسفل المنارة الشهيرة، يتعرج طريق رأس سبارطيل الساحلي فوق منحدرات خضراء ضخمة تغوص بشكل عمودي ومذهل في المحيط الهائج. توفر العديد من نقاط المشاهدة الطبيعية الصغيرة المرتبة على طول الطريق إطلالات خلابة على اللقاء المهيب بين أمواج المحيط الأطلسي القوية ومياه البحر الأبيض المتوسط الأكثر هدوءاً. إنه أحد أفضل الأماكن في المنطقة لتصوير الحياة البرية البحرية، والطيور المهاجرة، وقبل كل شيء، لمشاهدة واحد من أروع غروب للشمس في شمال أفريقيا بأكملها.",
4.8, 1200, 0, True, 20, 60, ["nature", "ocean", "panorama", "coucher_soleil"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?cliff,ocean,morocco", None, None)

add_lieu("lieu_026", "Corniche de Merkala", "viewpoint", "corniche", 35.7950, -5.8250, "Route de Merkala, Tanger 90000, Maroc", "Merkala",
"Nichée au pied des falaises de la colline de Marshan, la route de la Corniche de Merkala est un secret bien gardé des Tangérois. Cette promenade côtière récemment réaménagée relie la vieille ville au quartier résidentiel de Marshan en longeant l'océan au plus près des vagues. L'air y est pur, chargé d'embruns marins, et la vue sur la vieille forteresse portugaise et le détroit est tout simplement spectaculaire. C'est le spot de prédilection des coureurs matinaux et des familles qui s'y promènent au crépuscule pour respirer l'air vivifiant de la mer.",
"Nestled at the foot of the Marshan hill cliffs, the Merkala Corniche road is a well-kept secret among Tangier locals. This recently renovated coastal promenade connects the old town to the residential district of Marshan by running along the ocean right next to the crashing waves. The air is pure, laden with sea spray, and the view of the old Portuguese fortress and the strait is simply spectacular. It is the favorite spot for morning joggers and families strolling at dusk to breathe in the invigorating sea air.",
"يقع طريق كورنيش مرقالة عند سفح منحدرات تل المرشان، وهو سر محفوظ جيداً بين سكان طنجة الأصليين. يربط هذا الممشى الساحلي الذي تم تجديده مؤخراً البلدة القديمة بالحي السكني في المرشان من خلال السير بمحاذاة المحيط بالقرب من الأمواج المتلاطمة. الهواء هناك نقي ومحمل برذاذ البحر المنعش، والإطلالة على القلعة البرتغالية القديمة والمضيق مذهلة بكل بساطة. إنه المكان المفضل للعدائين في الصباح الباكر والعائلات التي تتنزه عند الغسق لاستنشاق هواء البحر المنعش وتجديد نشاطها.",
4.5, 600, 0, True, 45, 90, ["promenade", "mer", "corniche", "panorama"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?corniche,waves,tangier", None, None)

# 8 PARCS ET ESPACES VERTS
add_lieu("lieu_027", "Parc Perdicaris (Forêt de Rmilat)", "parc_espace_vert", "foret", 35.7900, -5.8500, "Forêt de Rmilat, Tanger 90000, Maroc", "Rmilat",
"Le Parc Perdicaris, situé dans la somptueuse forêt de Rmilat, est le véritable poumon vert de Tanger. Cet immense parc botanique naturel de près de 70 hectares abrite des centaines d'espèces de flore locale et exotique, notamment d'impressionnants eucalyptus, des chênes-lièges et des pins parasols géants. Le parc doit son nom au riche diplomate gréco-américain Ion Perdicaris qui y fit construire un château romantique pour son épouse. Des sentiers balisés permettent de longues randonnées ombragées, s'ouvrant régulièrement sur de magnifiques balcons naturels offrant des vues saisissantes sur le détroit de Gibraltar.",
"Perdicaris Park, located in the sumptuous Rmilat forest, is the true green lung of Tangier. This immense natural botanical park of nearly 70 hectares is home to hundreds of species of local and exotic flora, including impressive eucalyptus trees, cork oaks, and giant umbrella pines. The park is named after the wealthy Greek-American diplomat Ion Perdicaris, who built a romantic castle there for his wife. Marked trails allow for long shaded hikes, regularly opening onto magnificent natural balconies offering striking views of the Strait of Gibraltar.",
"منتزه بيرديكاريس، الواقع في غابة الرميلات الفخمة، هو الرئة الخضراء الحقيقية والمنعشة لمدينة طنجة. يضم هذا المنتزه النباتي الطبيعي الضخم الذي تبلغ مساحته حوالي 70 هكتاراً مئات الأنواع من النباتات المحلية والغريبة، بما في ذلك أشجار الأوكالبتوس المذهلة وبلوط الفلين وصنوبر المظلة العملاق. سمي المنتزه باسم الدبلوماسي اليوناني الأمريكي الثري إيون بيرديكاريس الذي بنى قلعة رومانسية هناك لزوجته. تتيح المسارات المحددة القيام بنزهات طويلة ومظللة، وتفتح بانتظام على شرفات طبيعية رائعة توفر إطلالات مذهلة على مضيق جبل طارق.",
4.8, 1600, 0, True, 90, 240, ["nature", "foret", "randonnee", "famille"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?forest,park,morocco", None, None)

add_lieu("lieu_028", "Jardins de la Mendoubia", "parc_espace_vert", "jardin_public", 35.7836, -5.8105, "Place du 9 Avril, Tanger 90000, Maroc", "Centre-ville",
"Les Jardins de la Mendoubia forment une oasis urbaine de paix et de verdure située en plein centre-ville, adossée à l'agitation trépidante du Grand Socco. L'attraction principale de ce parc ombragé est un spectaculaire banian géant vieux de plus de 800 ans, dont les racines aériennes impressionnantes émerveillent les promeneurs et les photographes. Ces jardins abritaient autrefois le tribunal des conflits internationaux, ajoutant une couche d'histoire à leur beauté naturelle. C'est l'endroit parfait pour une pause fraîcheur lors des chaudes journées d'été, offrant une halte de quiétude très appréciée des Tangérois.",
"The Mendoubia Gardens form an urban oasis of peace and greenery located right in the city center, backing onto the bustling Grand Socco. The main attraction of this shaded park is a spectacular giant banyan tree over 800 years old, whose impressive aerial roots marvel walkers and photographers alike. These gardens once housed the international conflict tribunal, adding a layer of history to their natural beauty. It is the perfect place for a refreshing break on hot summer days, offering a highly appreciated stop of tranquility for Tangier residents.",
"تشكل حدائق المندوبية واحة حضرية من السلام والمساحات الخضراء تقع في وسط المدينة مباشرة، خلف صخب ساحة السوق الكبير. نقطة الجذب الرئيسية في هذه الحديقة المظللة هي شجرة بانيان عملاقة مذهلة يبلغ عمرها أكثر من 800 عام، والتي تثير جذورها الهوائية الرائعة إعجاب المتنزهين والمصورين على حد سواء. كانت هذه الحدائق في الماضي تضم محكمة النزاعات الدولية، مما أضاف طبقة من العمق التاريخي إلى جمالها الطبيعي. إنها المكان المثالي لاستراحة منعشة في أيام الصيف الحارة، وتوفر محطة هدوء تحظى بتقدير كبير.",
4.4, 950, 0, True, 30, 60, ["jardin", "nature", "centre_ville", "detente"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?garden,banyan,tangier", None, None)

add_lieu("lieu_029", "Parc de la Villa Harris", "parc_espace_vert", "jardin_botanique", 35.7800, -5.7800, "Quartier Malabata, Tanger 90000, Maroc", "Malabata",
"Le parc luxuriant de la Villa Harris entoure un ancien manoir hispano-mauresque magnifiquement restauré. Ce vaste espace vert historique fut créé à la fin du XIXe siècle par Walter Burton Harris, le célèbre et extravagant correspondant spécial du journal The Times au Maroc. Le parc regorge d'essences végétales rares rapportées des quatre coins du monde lors de ses nombreux voyages. Ses allées ombragées, ses parterres de fleurs méticuleusement entretenus et la superbe architecture du bâtiment abritant désormais un musée d'art moderne en font une promenade raffinée alliant culture, histoire et botanique.",
"The lush park of Villa Harris surrounds a beautifully restored former Hispano-Moorish mansion. This vast historic green space was created in the late 19th century by Walter Burton Harris, the famous and extravagant special correspondent for The Times in Morocco. The park is full of rare plant species brought back from all over the world during his numerous travels. Its shaded paths, meticulously maintained flowerbeds, and the superb architecture of the building now housing a modern art museum make it a refined walk combining culture, history, and botany.",
"يحيط منتزه فيلا هاريس المورق بقصر إسباني-موريسكي قديم تم ترميمه بشكل جميل جداً. تم إنشاء هذه المساحة الخضراء التاريخية الشاسعة في أواخر القرن التاسع عشر على يد والتر بيرتون هاريس، المراسل الخاص الشهير والغريب الأطوار لصحيفة التايمز في المغرب. يزخر المنتزه بأنواع النباتات النادرة التي تم جلبها من جميع أنحاء العالم خلال رحلاته العديدة. أزقته المظللة، وأحواض الزهور المعتنى بها بدقة، والهندسة المعمارية الرائعة للمبنى الذي يضم الآن متحفاً للفن الحديث، تجعل منه نزهة راقية تجمع بين الثقافة والتاريخ وعلم النبات.",
4.6, 750, 0, True, 45, 90, ["parc", "botanique", "art", "histoire"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?park,villa,morocco", None, None)

add_lieu("lieu_030", "Donabo Botanical Gardens", "parc_espace_vert", "jardin_botanique", 35.7700, -5.9000, "Route de Cap Spartel, Tanger 90000, Maroc", "Cap Spartel",
"Situé dans un cadre exceptionnel de la forêt de Rmilat, non loin de l'océan Atlantique, le Donabo Botanical Gardens est une création écologique récente, dédiée à la préservation méticuleuse de la biodiversité régionale du Nord du Maroc. Ce jardin botanique, aménagé en terrasses douces, abrite d'innombrables espèces endémiques de la Méditerranée, des plantes médicinales rares et de magnifiques jardins fleuris très apaisants. Il abrite également un petit café écologique charmant, offrant l'opportunité de siroter un thé aux herbes fraîches du jardin tout en écoutant le chant enchanteur des oiseaux dans une sérénité totale.",
"Located in an exceptional setting within the Rmilat forest, not far from the Atlantic Ocean, the Donabo Botanical Gardens is a recent ecological creation dedicated to the meticulous preservation of Northern Morocco's regional biodiversity. This botanical garden, arranged in gentle terraces, houses countless endemic Mediterranean species, rare medicinal plants, and beautiful, highly soothing flower gardens. It also features a charming small eco-café, offering the opportunity to sip fresh herbal tea straight from the garden while listening to the enchanting birdsong in total serenity.",
"تقع حدائق دونابو النباتية في بيئة استثنائية داخل غابة الرميلات، غير بعيد عن المحيط الأطلسي، وهي إبداع بيئي حديث مخصص للحفاظ الدقيق على التنوع البيولوجي الإقليمي الفريد في شمال المغرب. تضم هذه الحديقة النباتية، المرتبة في مدرجات لطيفة، عدداً لا يحصى من الأنواع المتوطنة في منطقة البحر الأبيض المتوسط، والنباتات الطبية النادرة، وحدائق الزهور الجميلة والمهدئة للغاية. كما تضم مقهى بيئياً صغيراً وساحراً، يتيح لك فرصة احتساء شاي الأعشاب الطازج من الحديقة أثناء الاستماع إلى زقزقة الطيور الساحرة في هدوء وسكينة تامة.",
4.9, 450, 50, False, 60, 120, ["botanique", "nature", "ecologie", "detente"], ["printemps", "ete", "automne"], False, "https://source.unsplash.com/600x400/?botanical,garden,tangier", None, None)

add_lieu("lieu_031", "Forêt Diplomatique", "parc_espace_vert", "foret", 35.6800, -5.9200, "Route Asilah, Tanger 90000, Maroc", "Sud Tanger",
"S'étendant le long de la magnifique côte atlantique au sud de la ville, la vaste Forêt Diplomatique tire son nom de la période historique internationale où elle était un terrain de chasse exclusif et prisé des nombreux diplomates en poste à Tanger. Aujourd'hui ouverte à tous, cette forêt dense de pins parfumés, de chênes lièges et d'eucalyptus borde d'immenses plages de sable fin immaculées. C'est l'endroit parfait et très prisé des familles locales pour de longs pique-niques dominicaux, des promenades équestres ou de longues marches méditatives à l'ombre bienveillante des grands arbres.",
"Stretching along the magnificent Atlantic coast south of the city, the vast Diplomatic Forest takes its name from the historical international period when it was an exclusive hunting ground highly prized by the many diplomats stationed in Tangier. Today open to all, this dense forest of fragrant pines, cork oaks, and eucalyptus borders immense pristine sandy beaches. It is the perfect place, very popular with local families, for long Sunday picnics, horseback riding, or long meditative walks in the benevolent shade of the tall trees.",
"تمتد الغابة الدبلوماسية الشاسعة على طول ساحل المحيط الأطلسي الرائع جنوب المدينة، وتستمد اسمها من الفترة التاريخية الدولية عندما كانت منطقة صيد حصرية وذات قيمة عالية للدبلوماسيين العديدين المتمركزين في طنجة. هذه الغابة الكثيفة من أشجار الصنوبر العطرة وبلوط الفلين والأوكالبتوس مفتوحة اليوم للجميع، وتحدها شواطئ رملية واسعة ونقية. إنه المكان المثالي والذي يحظى بشعبية كبيرة بين العائلات المحلية لقضاء النزهات الطويلة يوم الأحد، أو ركوب الخيل، أو المشي التأملي الطويل في الظل الوارف للأشجار العالية.",
4.3, 560, 0, True, 120, 240, ["foret", "nature", "pique_nique", "randonnee"], ["printemps", "ete"], True, "https://source.unsplash.com/600x400/?pine,forest,ocean", None, None)

add_lieu("lieu_032", "Parc Sania", "parc_espace_vert", "jardin_public", 35.7720, -5.8200, "Avenue Sania, Tanger 90000, Maroc", "Centre-ville",
"Le Parc Sania est l'un des rares et précieux espaces verts de loisirs aménagés en plein cœur de la nouvelle ville moderne. Très bien entretenu et fleuri, ce parc compact mais élégant est structuré autour d'allées de palmiers dattiers, de petits bassins d'eau rafraîchissants et d'aires de jeux modernes et sécurisées. Particulièrement populaire auprès des familles marocaines en fin d'après-midi, c'est un excellent poste d'observation pour comprendre la vie quotidienne et sociale locale. Son ambiance paisible en fait un refuge idéal après une journée intensive de shopping au centre-ville.",
"Parc Sania is one of the rare and precious recreational green spaces laid out right in the heart of the modern new city. Very well maintained and full of flowers, this compact yet elegant park is structured around alleys of date palms, small refreshing water basins, and modern, safe playgrounds. Particularly popular with Moroccan families in the late afternoon, it is an excellent observation post to understand daily and social local life. Its peaceful atmosphere makes it an ideal refuge after an intensive day of shopping downtown.",
"منتزه السانية هو أحد المساحات الخضراء الترفيهية النادرة والثمينة الواقعة في قلب المدينة الجديدة الحديثة. تم تصميم هذا المنتزه المدمج والأنيق بشكل جيد للغاية ومليء بالزهور، وهو مبني حول أزقة من أشجار نخيل التمر، وأحواض مياه صغيرة منعشة، وملاعب حديثة وآمنة. يحظى بشعبية خاصة لدى العائلات المغربية في أواخر فترة ما بعد الظهر، وهو نقطة مراقبة ممتازة لفهم الحياة اليومية والاجتماعية المحلية عن قرب. أجواؤه الهادئة تجعله ملاذاً مثالياً للاسترخاء بعد يوم مكثف من التسوق في وسط المدينة.",
4.0, 320, 0, True, 30, 60, ["parc", "famille", "enfant", "detente"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?park,palmtree,tangier", None, None)

add_lieu("lieu_033", "Jardins de la Légation", "parc_espace_vert", "jardin_botanique", 35.7830, -5.8115, "Rue d'Amérique, Tanger 90000, Maroc", "Médina",
"Un joyau caché de pure tranquillité, niché secrètement au cœur même de la vibrante médina. Les jardins intérieurs de l'American Legation constituent un patio de style mauresque absolument exquis, avec ses zelliges complexes, sa fontaine murmure et ses plantes andalouses grimpantes. Bien qu'ils fassent partie intégrante du musée historique, beaucoup de visiteurs s'y attardent spécifiquement pour lire, écrire ou simplement méditer dans le calme absolu. C'est l'un des rares endroits dans la vieille ville où l'on entend plus le chant des oiseaux que les bruits de la rue avoisinante.",
"A hidden jewel of pure tranquility, secretly nestled in the very heart of the vibrant medina. The interior gardens of the American Legation constitute an absolutely exquisite Moorish-style patio, complete with its intricate zelliges, murmuring fountain, and climbing Andalusian plants. Although they are an integral part of the historical museum, many visitors linger here specifically to read, write, or simply meditate in absolute silence. It is one of the rare places in the old town where the singing of birds is louder than the noises of the nearby street.",
"جوهرة خفية من الهدوء الخالص، تقع سراً في قلب المدينة العتيقة النابضة بالحياة. تشكل الحدائق الداخلية للمفوضية الأمريكية فناءً رائعاً للغاية على الطراز الموريسكي، مع الزليج المعقد والنافورة ذات الخرير المريح والنباتات الأندلسية المتسلقة. وعلى الرغم من كونها جزءاً لا يتجزأ من المتحف التاريخي، إلا أن العديد من الزوار يقضون وقتاً طويلاً فيها خصيصاً للقراءة أو الكتابة أو مجرد التأمل في صمت وهدوء مطلقين. إنها واحدة من الأماكن النادرة في البلدة القديمة حيث يكون غناء الطيور مسموعاً أكثر من ضجيج الشارع القريب.",
4.6, 500, 20, False, 30, 60, ["jardin", "musee", "calme", "histoire"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?courtyard,garden,morocco", None, None)

add_lieu("lieu_034", "Parc de Boukhalef", "parc_espace_vert", "parc_naturel", 35.7200, -5.8800, "Zone Boukhalef, Tanger 90000, Maroc", "Boukhalef",
"Un vaste espace vert aménagé plus récemment près de la nouvelle université, le Parc de Boukhalef représente la volonté de la ville d'offrir des espaces récréatifs de grande qualité loin du centre historique. Autour d'un vaste lac artificiel très photogénique se déploient de multiples sentiers goudronnés parfaits pour la course à pied, le vélo ou le roller. De nombreuses aires de pique-nique ombragées en font une destination prisée le week-end. L'endroit est particulièrement agréable au crépuscule, lorsque les étudiants et les familles locales viennent s'y détendre en nombre.",
"A vast, more recently developed green space near the new university, Boukhalef Park represents the city's desire to offer high-quality recreational spaces away from the historic center. Around a large, highly photogenic artificial lake unfold multiple paved paths perfect for running, cycling, or rollerblading. Numerous shaded picnic areas make it a popular weekend destination. The place is particularly pleasant at dusk, when students and local families come in large numbers to relax and unwind.",
"يعد منتزه بوخالف مساحة خضراء شاسعة تم تطويرها مؤخراً بالقرب من الجامعة الجديدة، وهو يمثل بوضوح رغبة المدينة في توفير مساحات ترفيهية عالية الجودة بعيداً عن المركز التاريخي. حول بحيرة اصطناعية ضخمة ومناسبة جداً للتصوير، تنتشر مسارات معبدة متعددة ومثالية للركض أو ركوب الدراجات العادية أو التزلج على العجلات. تجعل منه العديد من مناطق التنزه المظللة وجهة شهيرة جداً في عطلة نهاية الأسبوع. المكان ممتع بشكل خاص عند الغسق، عندما يأتي الطلاب والعائلات المحلية بأعداد كبيرة للاسترخاء فيه.",
4.1, 400, 0, True, 45, 90, ["parc", "sport", "lac", "famille"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?park,lake,tangier", None, None)

# 8 MARCHES ET SOUKS
add_lieu("lieu_035", "Marché Central de Tanger", "marche_souk", "marche_couvert", 35.7820, -5.8080, "Rue de la Liberté, Tanger 90000, Maroc", "Centre-ville",
"Construit en 1928, le pittoresque Marché Central couvert de Tanger est une véritable explosion symphonique de couleurs éclatantes, d'odeurs intenses et de bruits quotidiens de la vie marocaine. On y trouve absolument tout l'art culinaire marocain : des pyramides vertigineuses d'épices parfumées, des montagnes d'olives marinées de toutes les couleurs, des fruits exotiques gorgés de soleil, et bien sûr, une halle aux poissons remarquablement animée. C'est l'endroit parfait, incontournable et authentique pour acheter des souvenirs gastronomiques savoureux et interagir avec les marchands locaux qui sont de redoutables négociateurs.",
"Built in 1928, the picturesque covered Central Market of Tangier is a true symphonic explosion of vibrant colors, intense smells, and the daily noises of Moroccan life. Here you can find absolutely all of Moroccan culinary art: dizzying pyramids of fragrant spices, mountains of marinated olives of all colors, sun-drenched exotic fruits, and of course, a remarkably lively fish hall. It is the perfect, essential, and authentic place to buy tasty gastronomic souvenirs and interact with local merchants who are formidable negotiators.",
"تم بناء السوق المركزي المغطى والخلاب في طنجة عام 1928، وهو يمثل انفجاراً سيمفونياً حقيقياً للألوان الزاهية والروائح الشديدة والضوضاء اليومية للحياة المغربية النابضة. يمكنك أن تجد فيه كل فنون الطهي المغربي بلا استثناء: أهرامات هائلة من التوابل العطرة، وجبال من الزيتون المتبل بجميع الألوان، والفواكه الاستوائية المليئة بالشمس، وبالطبع قاعة أسماك حيوية ونشطة بشكل ملحوظ. إنه المكان المثالي والأساسي والأصيل لشراء هدايا تذكارية شهية والتفاعل المباشر مع التجار المحليين الذين يعتبرون مفاوضين بارعين جداً.",
4.4, 2500, 0, True, 30, 90, ["marche", "gastronomie", "shopping", "local"], ["printemps", "ete", "automne", "hiver"], True, "https://source.unsplash.com/600x400/?market,spices,morocco", None, None)

add_lieu("lieu_036", "Marché de Casa Barata", "marche_souk", "marche_aux_puces", 35.7500, -5.8200, "Route de Rabat, Tanger 90000, Maroc", "Beni Makada",
"Immense, tentaculaire, chaotique et fascinant, le marché de Casa Barata (la maison bon marché) est le plus grand souk aux puces de la ville de Tanger. On peut littéralement y trouver de tout, de l'antiquité rare et précieuse aux appareils électroniques d'occasion, en passant par de superbes tapis berbères tissés à la main et des meubles d'époque. L'ambiance y est électrique, bruyante et 100% authentique, car c'est avant tout le marché des locaux. Fouiller dans ses dizaines d'allées labyrinthiques nécessite patience et sens de la négociation aiguisé.",
"Immense, sprawling, chaotic, and fascinating, the Casa Barata market (the cheap house) is the largest flea market in the city of Tangier. You can literally find everything here, from rare and precious antiques to second-hand electronics, including superb hand-woven Berber rugs and period furniture. The atmosphere is electric, noisy, and 100% authentic, as it is primarily a market for locals. Rummaging through its dozens of labyrinthine aisles requires immense patience and a sharp sense of negotiation.",
"سوق كاسا باراطا (البيت الرخيص) هو سوق هائل ومترامي الأطراف وفوضوي ورائع، وهو أكبر سوق للسلع المستعملة في مدينة طنجة بأكملها. يمكنك حرفياً العثور على أي شيء فيه، من التحف النادرة والثمينة إلى الأجهزة الإلكترونية المستعملة، بما في ذلك السجاد الأمازيغي الرائع المنسوج يدوياً والأثاث العتيق. الجو هناك مكهرب وصاخب وأصيل 100٪، لأنه في المقام الأول سوق للسكان المحليين. يتطلب البحث في العشرات من أزقته التي تشبه المتاهة المليئة بالأسرار صبراً كبيراً وحساً حاداً للتفاوض والمساومة.",
4.0, 1100, 0, True, 90, 180, ["marche", "antiquite", "insolite", "local"], ["printemps", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?fleamarket,souk,tangier", None, None)

add_lieu("lieu_037", "Souk Barra", "marche_souk", "souk", 35.7830, -5.8110, "Place du 9 Avril, Tanger 90000, Maroc", "Médina",
"Situé immédiatement à la lisière de la porte principale de la médina, le Souk Barra est un grand marché de plein air très animé. C'est ici que convergent depuis des générations les paysans et les femmes Jebli du Rif vêtues de leurs tenues traditionnelles rouges et blanches et coiffées de leurs grands chapeaux de paille pour vendre les produits frais de leurs fermes : légumes, fromages frais de chèvre, herbes aromatiques et artisanat rustique. C'est le paradis absolu des photographes à la recherche du vrai visage rural du Nord du Maroc.",
"Located immediately at the edge of the medina's main gate, the Souk Barra is a large, highly animated open-air market. This is where, for generations, peasants and Jebli women from the Rif, dressed in their traditional red and white outfits and wearing their large straw hats, converge to sell the fresh produce from their farms: vegetables, fresh goat cheeses, aromatic herbs, and rustic crafts. It is the absolute paradise for photographers looking to capture the true rural face of Northern Morocco.",
"يقع سوق برا (السوق الخارجي) مباشرة على حافة البوابة الرئيسية للمدينة العتيقة، وهو سوق كبير ومفتوح ومزدحم للغاية في الهواء الطلق. هنا، ولأجيال عديدة، يتجمع الفلاحون ونساء جبالة من منطقة الريف، مرتديات أزيائهن التقليدية ذات اللونين الأحمر والأبيض وقبعات القش الكبيرة والمميزة، لبيع المنتجات الطازجة من مزارعهم: خضروات، جبن ماعز طازج، أعشاب عطرية، وحرف ريفية بسيطة. إنه الجنة المطلقة للمصورين الباحثين عن التقاط الوجه الريفي الحقيقي والأصيل لقرى ومناطق شمال المغرب.",
4.6, 920, 0, True, 30, 60, ["souk", "tradition", "photographie", "produits_locaux"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?market,people,morocco", None, None)

add_lieu("lieu_038", "Souk Dakhil", "marche_souk", "souk", 35.7850, -5.8120, "Petit Socco, Tanger 90000, Maroc", "Médina",
"Le Souk Dakhil, le « marché intérieur », s'articule autour des ruelles étroites et entrelacées qui partent de la célèbre place du Petit Socco. C'est une véritable caverne d'Ali Baba dédiée à l'artisanat purement marocain. Vous y trouverez des échoppes regorgeant de maroquinerie odorante, de bijoux en argent berbère, de lanternes en cuivre ciselé, de poteries colorées et d'habits traditionnels. L'odeur du cuir, des épices et du cèdre se mêlent en permanence. Il est fortement conseillé de s'y perdre, de discuter avec les artisans et de s'essayer à l'art de la négociation amicale.",
"The Souk Dakhil, the 'inner market', revolves around the narrow, intertwined alleys radiating from the famous Petit Socco square. It is a true Aladdin's cave dedicated to purely Moroccan craftsmanship. Here you will find stalls overflowing with fragrant leather goods, Berber silver jewelry, chiseled copper lanterns, colorful pottery, and traditional clothing. The smell of leather, spices, and cedar mixes constantly in the air. It is highly recommended to get lost here, chat with the artisans, and try your hand at the art of friendly negotiation.",
"يتمحور سوق الداخل (السوق الداخلي) حول الأزقة الضيقة والمتشابكة التي تنطلق من ساحة السوق الصغير الشهيرة جداً. إنه كهف علي بابا حقيقي ومذهل مخصص للحرف اليدوية المغربية الخالصة. ستجد هنا أكشاكاً ومتاجر تفيض بالمصنوعات الجلدية العطرة، والمجوهرات الفضية الأمازيغية، والفوانيس النحاسية المنحوتة، والفخار الملون، والملابس التقليدية الأنيقة. تمتزج رائحة الجلد والتوابل وخشب الأرز باستمرار في الهواء. يُنصح بشدة بالضياع في هذا المكان، والتحدث الودي مع الحرفيين المهرة، وتجربة فن التفاوض الودي للحصول على أفضل الأسعار.",
4.7, 1850, 0, True, 60, 180, ["souk", "artisanat", "shopping", "medina"], ["printemps", "ete", "automne", "hiver"], False, "https://source.unsplash.com/600x400/?souk,crafts,tangier", None, None)

add_lieu("lieu_039", "Souk des Potiers", "marche_souk", "marche_specialise", 35.7800, -5.8050, "Bordure de la Médina, Tanger 90000, Maroc", "Médina",
"Bien que plus petit et moins connu que les grands souks touristiques, ce regroupement de marchands de céramique est le lieu parfait pour acquérir des poteries locales authentiques du Nord du Maroc, sans le stress des grandes foules. Contrairement à la poterie bleue de Fès ou colorée de Safi, le style traditionnel du Rif se distingue par son argile claire et ses délicats motifs géométriques simples en manganèse et ocre rouge. Les prix y sont souvent beaucoup plus justes et l'atmosphère y est nettement plus détendue et propice à l'échange.",
"Although smaller and less well-known than the large tourist souks, this gathering of ceramic merchants is the perfect place to acquire authentic local pottery from Northern Morocco, without the stress of huge crowds. Unlike the blue pottery of Fez or the colorful pottery of Safi, the traditional Rif style is distinguished by its light clay and delicate, simple geometric patterns in manganese and red ochre. Prices here are often much fairer, and the atmosphere is significantly more relaxed and conducive to friendly exchange with the sellers.",
"على الرغم من أنه أصغر حجماً وأقل شهرة من الأسواق السياحية الكبيرة، إلا أن هذا التجمع لتجار الخزف هو المكان المثالي بلا شك للحصول على فخار محلي أصيل من شمال المغرب، دون التعرض لضغط الزحام الكبير. على عكس فخار فاس الأزرق أو فخار آسفي الملون، يتميز طراز الريف التقليدي بطينه الفاتح وأنماطه الهندسية البسيطة والحساسة والمصنوعة من المنغنيز والمغرة الحمراء. غالباً ما تكون الأسعار هنا أكثر إنصافاً وواقعية، والجو العام أكثر استرخاءً ويشجع على التبادل الودي والحديث مع البائعين.",
4.3, 340, 0, True, 20, 45, ["souk", "artisanat", "poterie", "shopping"], ["printemps", "ete", "automne"], True, "https://source.unsplash.com/600x400/?pottery,market,morocco", None, None)

add_lieu("lieu_040", "Marché de Fondouk Chejra", "marche_souk", "artisanat", 35.7835, -5.8085, "Près de Rue d'Italie, Tanger 90000, Maroc", "Médina",
"Le Fondouk Chejra est un caravansérail historique miraculeusement préservé, aujourd'hui exclusivement consacré aux tisserands traditionnels de Tanger. Dans une cour ombragée à l'architecture andalouse, le son rythmique et presque hypnotique des anciens métiers à tisser manuels résonne du matin au soir. C'est l'un des rares endroits au Maroc où l'on peut encore observer la fabrication minutieuse des lourdes couvertures traditionnelles, des mendils rayés portés par les femmes du Rif et des tapis ruraux, le tout dans une atmosphère de travail acharné et d'artisanat séculaire qui force le respect.",
"Fondouk Chejra is a miraculously preserved historic caravanserai, today exclusively dedicated to the traditional weavers of Tangier. In a shaded courtyard with Andalusian architecture, the rhythmic and almost hypnotic sound of ancient manual looms resonates from morning to evening. It is one of the rare places in Morocco where one can still observe the meticulous manufacturing of heavy traditional blankets, the striped mendils worn by Rif women, and rural rugs, all in an atmosphere of hard work and secular craftsmanship that commands absolute respect.",
"فندق الشجرة هو خان تاريخي (كاروانسراي) محفوظ بأعجوبة، وهو مخصص اليوم حصرياً للنساجين التقليديين المهرة في طنجة. في ساحة فناء مظللة ذات هندسة معمارية أندلسية، يتردد الصوت الإيقاعي والمغناطيسي تقريباً للأنوال اليدوية القديمة من الصباح الباكر حتى المساء. إنه واحد من الأماكن النادرة في المغرب حيث لا يزال بإمكان المرء مراقبة التصنيع الدقيق للبطانيات التقليدية الثقيلة، والمناديل المخططة التي ترتديها نساء الريف، والسجاد الريفي، كل ذلك في جو من العمل الجاد والحرفية العلمانية التي تفرض الاحترام العميق.",
4.8, 620, 0, True, 30, 60, ["artisanat", "tissage", "histoire", "authentique"], ["printemps", "automne"], False, "https://source.unsplash.com/600x400/?weaver,loom,morocco", None, None)

with open(r'c:\Users\HP\Documents\projet touristique\dataset\lieux_touristiques.json', 'w', encoding='utf-8') as f:
    json.dump(lieux, f, ensure_ascii=False, indent=2)

print(f'Part 2: Total {len(lieux)} lieux saved so far')
