import json
import random

templates_fr = [
    "Pour bien préparer votre séjour à Tanger, voici les informations essentielles : {spec}. C'est une particularité de notre belle ville du détroit qu'il est bon de garder à l'esprit. Tanger est très accueillante et tout est pensé pour faciliter la vie des visiteurs. N'hésitez pas à demander conseil aux Tangérois qui se feront un plaisir de vous guider et de partager avec vous l'amour de leur ville. La convivialité est ici une règle d'or.",
    "Voici ce que vous devez absolument savoir pour votre visite à Tanger concernant ce point précis : {spec}. La ville de Tanger, véritable carrefour culturel entre l'Europe et l'Afrique, offre de multiples options pour rendre votre expérience inoubliable. Prenez toujours le temps de bien planifier ces petits détails pratiques, cela vous permettra de vous concentrer pleinement sur la découverte de nos magnifiques paysages et de nos richesses historiques.",
    "C'est une excellente question, très fréquente chez les voyageurs visitant Tanger. {spec}. En gardant cette information bien en tête, vous éviterez les mauvaises surprises et gagnerez un temps précieux lors de vos déplacements. N'oubliez pas que l'atmosphère tangéroise est avant tout détendue et chaleureuse, alors profitez-en à votre propre rythme, sans vous presser, et laissez-vous simplement charmer par la magie unique de la ville blanche."
]

templates_en = [
    "To help you prepare for your stay in Tangier, here is the essential information: {spec}. This is a particularity of our beautiful city of the strait that is good to keep in mind. Tangier is very welcoming and everything is designed to make life easier for visitors. Do not hesitate to ask the locals for advice; they will be genuinely happy to guide you and share their love for their city. Conviviality is a golden rule here.",
    "Here is what you absolutely need to know for your visit to Tangier regarding this specific point: {spec}. The city of Tangier, a true cultural crossroads between Europe and Africa, offers multiple options to make your experience unforgettable. Always take the time to plan these practical details well; it will allow you to fully focus on discovering our beautiful landscapes and historical treasures.",
    "This is an excellent question, very common among travelers visiting Tangier. {spec}. Keeping this information in mind will help you avoid bad surprises and save precious time during your travels. Remember that the atmosphere in Tangier is above all relaxed and warm, so enjoy it at your own pace, without rushing, and simply let yourself be charmed by the unique magic of the white city."
]

templates_ar = [
    "لإعداد إقامتك في طنجة بشكل جيد، إليك المعلومات الأساسية: {spec}. هذه ميزة خاصة لمدينتنا الجميلة على المضيق والتي من الجيد وضعها في الاعتبار دائماً. طنجة وجهة ترحيبية للغاية وكل شيء مصمم لتسهيل حياة الزوار. لا تتردد أبداً في طلب المشورة من سكان طنجة الذين سيكونون سعداء جداً بتوجيهك ومشاركة حبهم لمدينتهم معك، فالضيافة هنا قاعدة ذهبية متأصلة.",
    "إليك ما تحتاج بالتأكيد لمعرفته لزيارتك إلى طنجة بخصوص هذه النقطة المحددة: {spec}. تقدم مدينة طنجة، وهي ملتقى ثقافي حقيقي بين أوروبا وأفريقيا، خيارات متعددة لجعل تجربتك لا تُنسى. خذ دائماً الوقت الكافي للتخطيط لهذه التفاصيل العملية جيداً، فهذا سيتيح لك التركيز بشكل كامل على اكتشاف مناظرنا الطبيعية الخلابة وكنوزنا التاريخية العظيمة.",
    "هذا سؤال ممتاز وشائع جداً بين المسافرين الذين يزورون طنجة. {spec}. سيساعدك وضع هذه المعلومات في الاعتبار على تجنب المفاجآت السيئة وتوفير الوقت الثمين أثناء تنقلاتك. تذكر أن الجو في طنجة مريح ودافئ قبل كل شيء، لذا استمتع به بالسرعة التي تناسبك، دون استعجال، ودع سحر المدينة البيضاء الفريد يأخذك في رحلة رائعة."
]

facts = [
    # TRANSPORT (8)
    ("transport", "aeroport", "Comment aller de l'aéroport au centre-ville ?", "How to go from the airport to the city center?", "كيف تذهب من المطار إلى وسط المدينة؟",
     "L'aéroport Ibn Battuta est à 15km. Le taxi coûte environ 150 MAD. Vous pouvez aussi prendre le bus urbain Ligne 9",
     "Ibn Battuta airport is 15km away. A taxi costs around 150 MAD. You can also take the urban bus Line 9",
     "مطار ابن بطوطة يبعد 15 كم. سيارة الأجرة تكلف حوالي 150 درهم. يمكنك أيضاً ركوب حافلة المدينة خط 9"),
    ("transport", "petits_taxis", "Comment fonctionnent les petits taxis ?", "How do petit taxis work?", "كيف تعمل سيارات الأجرة الصغيرة؟",
     "Les petits taxis sont bleus à Tanger et utilisent obligatoirement un compteur. Ils ne peuvent pas sortir de la ville",
     "Petit taxis are blue in Tangier and must use a meter. They cannot go outside the city limits",
     "سيارات الأجرة الصغيرة زرقاء في طنجة وتستخدم العداد. لا يمكنها الخروج من حدود المدينة"),
    ("transport", "grands_taxis", "Où prendre un grand taxi ?", "Where to take a grand taxi?", "أين أستقل سيارة أجرة كبيرة؟",
     "Les grands taxis de couleur crème suivent des itinéraires fixes vers l'extérieur (Cap Spartel, Asilah) avec des tarifs partagés économiques",
     "Cream-colored grand taxis follow fixed routes outside (Cape Spartel, Asilah) with economical shared fares",
     "سيارات الأجرة الكبيرة ذات اللون الكريمي تتبع مسارات ثابتة للخارج بتسعيرة مشتركة واقتصادية"),
    ("transport", "train_tgv", "Où se trouve la gare TGV ?", "Where is the TGV train station?", "أين تقع محطة قطار البراق؟",
     "La gare de Tanger Ville est très centrale. Le TGV Al Boraq permet de rejoindre Casablanca en seulement 2h10",
     "Tangier Ville station is very central. The Al Boraq high-speed train connects to Casablanca in just 2h10",
     "محطة طنجة المدينة مركزية. يتيح قطار البراق فائق السرعة الوصول إلى الدار البيضاء في ساعتين وعشر دقائق فقط"),
    ("transport", "bus", "Quel est le prix du bus urbain ?", "What is the price of the urban bus?", "ما هو سعر حافلة المدينة؟",
     "Le réseau est géré par la société ALSA. Le ticket coûte environ 4 MAD, ce qui est très pratique",
     "The network is managed by the ALSA company. A ticket costs around 4 MAD, which is very convenient",
     "تدير شركة ألزا شبكة الحافلات. يبلغ سعر التذكرة حوالي 4 دراهم، وهو عملي ومريح جداً"),
    ("transport", "location_voiture", "Où louer une voiture ?", "Where to rent a car?", "أين أستأجر سيارة؟",
     "Vous trouverez de nombreuses agences de location fiables à l'aéroport ou directement sur le Boulevard Pasteur en centre-ville",
     "You will find many reliable rental agencies at the airport or directly on Boulevard Pasteur in the city center",
     "ستجد العديد من وكالات التأجير الموثوقة في المطار أو مباشرة في شارع باستور بوسط المدينة"),
    ("transport", "medina_marche", "Peut-on rouler dans la médina ?", "Can you drive in the medina?", "هل يمكن القيادة في المدينة القديمة؟",
     "La médina est entièrement piétonne. Préparez de bonnes chaussures de marche car les ruelles sont souvent étroites et en pente",
     "The medina is entirely pedestrian. Prepare good walking shoes as the alleys are often narrow and steep",
     "المدينة القديمة مخصصة للمشاة بالكامل. جهز أحذية مشي جيدة لأن الأزقة غالباً ما تكون ضيقة ومنحدرة"),
    ("transport", "ferry_espagne", "Comment prendre le ferry pour l'Espagne ?", "How to take the ferry to Spain?", "كيف أستقل العبارة إلى إسبانيا؟",
     "Les ferrys rapides FRS depuis le port de Tanger Ville mettent environ une heure pour rejoindre Tarifa en Espagne",
     "Fast FRS ferries from Tangier Ville port take about an hour to reach Tarifa in Spain",
     "تستغرق العبارات السريعة من ميناء طنجة المدينة حوالي ساعة للوصول إلى طريفة في إسبانيا"),

    # LIEUX (12)
    ("lieux", "grottes_hercule", "Comment visiter les Grottes d'Hercule ?", "How to visit the Caves of Hercules?", "كيف أزور مغارات هرقل؟",
     "Les grottes sont à 14km du centre. C'est un site naturel mythique avec une ouverture spectaculaire en forme d'Afrique",
     "The caves are 14km from the center. It's a mythical natural site with a spectacular opening shaped like Africa",
     "المغارات تبعد 14 كم عن المركز. إنه موقع طبيعي أسطوري بفتحة مذهلة على شكل قارة أفريقيا"),
    ("lieux", "cap_spartel", "Que voir au Cap Spartel ?", "What to see at Cape Spartel?", "ماذا أرى في رأس سبارطيل؟",
     "Le Cap Spartel est le point de rencontre exact entre l'Océan Atlantique et la mer Méditerranée, célèbre pour son magnifique phare",
     "Cape Spartel is the exact meeting point between the Atlantic Ocean and the Mediterranean Sea, famous for its magnificent lighthouse",
     "رأس سبارطيل هو نقطة الالتقاء الدقيقة بين المحيط الأطلسي والبحر الأبيض المتوسط، ويشتهر بمنارته المذهلة"),
    ("lieux", "kasbah", "Qu'y a-t-il dans la Kasbah ?", "What is in the Kasbah?", "ماذا يوجد في القصبة؟",
     "La Kasbah offre une vue imprenable sur le détroit. Vous y trouverez aussi l'excellent musée de la Kasbah des cultures méditerranéennes",
     "The Kasbah offers stunning views of the strait. You will also find the excellent Kasbah Museum of Mediterranean Cultures there",
     "توفر القصبة إطلالة خلابة على المضيق. ستجد هناك أيضاً متحف القصبة للثقافات المتوسطية الممتاز"),
    ("lieux", "grand_socco", "Où se trouve le Grand Socco ?", "Where is the Grand Socco?", "أين يقع السوق الكبير؟",
     "Le Grand Socco, ou Place du 9 Avril, marque la frontière animée entre la ville nouvelle moderne et l'ancienne médina",
     "The Grand Socco, or April 9 Square, marks the bustling border between the modern new city and the old medina",
     "السوق الكبير، أو ساحة 9 أبريل، يمثل الحدود النابضة بالحياة بين المدينة الجديدة الحديثة والمدينة القديمة"),
    ("lieux", "petit_socco", "Pourquoi le Petit Socco est-il célèbre ?", "Why is the Petit Socco famous?", "لماذا يشتهر السوق الصغير؟",
     "C'est une petite place historique au coeur de la médina, entourée de cafés anciens où se réunissaient autrefois les écrivains internationaux",
     "It is a historic little square in the heart of the medina, surrounded by old cafes where international writers used to gather",
     "إنها ساحة تاريخية صغيرة في قلب المدينة القديمة، محاطة بمقاهي قديمة حيث كان يجتمع الكتاب الدوليون"),
    ("lieux", "cafe_hafa", "Où se trouve le Café Hafa ?", "Where is Cafe Hafa?", "أين يقع مقهى الحافة؟",
     "Ouvert en 1921 dans le quartier Marshan, il offre un thé à la menthe parfait avec une vue en terrasses mémorable sur l'Espagne",
     "Opened in 1921 in the Marshan district, it offers perfect mint tea with a memorable terraced view of Spain",
     "افتتح عام 1921 في حي مرشان، ويقدم شاي النعناع المثالي مع إطلالة مدرجة لا تُنسى على إسبانيا"),
    ("lieux", "parc_perdicaris", "Peut-on faire de la randonnée à Tanger ?", "Can you hike in Tangier?", "هل يمكن ممارسة رياضة المشي في طنجة؟",
     "Oui, le somptueux Parc Perdicaris (forêt de Rmilat) est parfait pour marcher en pleine nature avec une vue plongeante sur l'océan",
     "Yes, the sumptuous Perdicaris Park (Rmilat forest) is perfect for walking in nature with a plunging view of the ocean",
     "نعم، منتزه بيرديكاريس الفاخر (غابة الرميلات) مثالي للمشي في الطبيعة مع إطلالة رائعة على المحيط"),
    ("lieux", "legation_americaine", "Que voir au musée de la Légation Américaine ?", "What to see at the American Legation museum?", "ماذا أرى في متحف المفوضية الأمريكية؟",
     "C'est la première propriété diplomatique américaine au monde. Elle abrite des expositions fascinantes sur l'histoire maroco-américaine en pleine médina",
     "It is the first American diplomatic property in the world. It houses fascinating exhibitions on Moroccan-American history right in the medina",
     "إنها أول ملكية دبلوماسية أمريكية في العالم. تضم معارض رائعة عن التاريخ المغربي الأمريكي في قلب المدينة القديمة"),
    ("lieux", "corniche", "Où se promener le soir ?", "Where to walk in the evening?", "أين أتنزه في المساء؟",
     "La longue Corniche de Tanger s'étendant le long de la plage municipale est idéale pour une balade nocturne vivante et en toute sécurité",
     "The long Tangier Corniche stretching along the municipal beach is ideal for a lively and completely safe night walk",
     "كورنيش طنجة الطويل الممتد على طول شاطئ البلدية مثالي لنزهة ليلية حيوية وآمنة تماماً"),
    ("lieux", "plage_achakkar", "Quelle est la meilleure plage près de Tanger ?", "What is the best beach near Tangier?", "ما هو أفضل شاطئ بالقرب من طنجة؟",
     "La plage d'Achakkar, située tout près des grottes d'Hercule, offre une belle étendue de sable fin très prisée des familles",
     "Achakkar beach, located very close to the Caves of Hercules, offers a beautiful stretch of fine sand very popular with families",
     "يقدم شاطئ أشقار، الواقع بالقرب من مغارات هرقل، امتداداً جميلاً من الرمال الناعمة التي تحظى بشعبية كبيرة لدى العائلات"),
    ("lieux", "asilah", "Faut-il visiter Asilah ?", "Should I visit Asilah?", "هل يجب زيارة أصيلة؟",
     "Absolument, Asilah est une charmante ville côtière à 45km, réputée mondialement pour sa médina blanche immaculée et ses fresques murales",
     "Absolutely, Asilah is a charming coastal town 45km away, world-renowned for its pristine white medina and beautiful murals",
     "بالتأكيد، أصيلة مدينة ساحلية ساحرة تبعد 45 كم، تشتهر عالمياً بمدينتها البيضاء النقية وجدارياتها الجميلة"),
    ("lieux", "chefchaouen", "Combien de temps pour aller à Chefchaouen ?", "How long to go to Chefchaouen?", "كم يستغرق الذهاب إلى شفشاون؟",
     "Il faut compter environ 2 heures de route panoramique. La fameuse ville bleue est l'excursion d'une journée la plus populaire depuis Tanger",
     "It takes about 2 hours of scenic driving. The famous blue city is the most popular day trip from Tangier",
     "يستغرق الأمر حوالي ساعتين من القيادة ذات المناظر الخلابة. المدينة الزرقاء الشهيرة هي الرحلة اليومية الأكثر شعبية من طنجة"),

    # RESTAURANTS (8)
    ("restaurants", "cuisine_marocaine", "Où manger de la cuisine marocaine authentique ?", "Where to eat authentic Moroccan cuisine?", "أين أتناول المطبخ المغربي الأصيل؟",
     "Des établissements incontournables comme Dar Naji ou le Restaurant Rif Kebdani proposent des tajines et des couscous traditionnels délicieux",
     "Must-visit establishments like Dar Naji or Restaurant Rif Kebdani offer delicious and truly traditional tagines and couscous",
     "تقدم مؤسسات لا غنى عن زيارتها مثل دار ناجي أو مطعم ريف كبداني طواجن وكسكس تقليدي لذيذ وأصيل"),
    ("restaurants", "fruits_mer", "Où manger les meilleurs fruits de mer ?", "Where to eat the best seafood?", "أين أتناول أفضل المأكولات البحرية؟",
     "Les restaurants situés juste à côté du vieux port de pêche vous garantissent des poissons et fruits de mer d'une fraîcheur exceptionnelle",
     "The restaurants located right next to the old fishing port guarantee you exceptionally fresh fish and delicious seafood",
     "تضمن المطاعم الواقعة بجوار ميناء الصيد القديم أسماكاً ومأكولات بحرية طازجة بشكل استثنائي ولذيذ"),
    ("restaurants", "tapas_espagnoles", "Peut-on manger espagnol à Tanger ?", "Can you eat Spanish food in Tangier?", "هل يمكن تناول الطعام الإسباني في طنجة؟",
     "L'héritage espagnol y est très fort. La Casa de Espana ou le restaurant Anna & Paolo servent de formidables tapas et paellas",
     "The Spanish heritage is very strong here. Casa de Espana or Anna & Paolo restaurant serve wonderful tapas and authentic paellas",
     "التراث الإسباني قوي جداً هنا. تقدم كازا دي إسبانيا أو مطعم آنا وباولو تاباس رائعة وباييلا أصلية"),
    ("restaurants", "petit_dejeuner", "Que manger au petit-déjeuner ?", "What to eat for breakfast?", "ماذا أتناول على الفطور؟",
     "Testez la soupe de fèves (bissara) ou les crêpes marocaines (msemmen) accompagnées de thé à la menthe dans les cafés de la médina",
     "Test the broad bean soup (bissara) or Moroccan pancakes (msemmen) accompanied by mint tea in the old medina cafes",
     "جرب حساء الفول (البيصارة) أو الفطائر المغربية (المسمن) مصحوبة بشاي النعناع في مقاهي المدينة القديمة"),
    ("restaurants", "cafe_historique", "Quels sont les cafés historiques ?", "What are the historic cafes?", "ما هي المقاهي التاريخية؟",
     "Outre l'incontournable Café Hafa, le Café Baba dans la Kasbah est mythique pour avoir jadis accueilli des stars comme les Rolling Stones",
     "Besides the unmissable Cafe Hafa, Cafe Baba in the Kasbah is legendary for having once hosted stars like the Rolling Stones",
     "إلى جانب مقهى الحافة الذي لا يفوت، يعتبر مقهى بابا في القصبة أسطورياً لاستضافته قديماً نجوماً مثل رولينج ستونز"),
    ("restaurants", "restaurant_vue", "Quel restaurant a la meilleure vue ?", "Which restaurant has the best view?", "أي مطعم لديه أفضل إطلالة؟",
     "Le luxueux Morocco Club dans la Kasbah ou les superbes terrasses de l'hôtel El Minzah offrent des dîners raffinés avec des vues panoramiques",
     "The luxurious Morocco Club in the Kasbah or the superb terraces of the El Minzah hotel offer fine dining with panoramic views",
     "نادي المغرب الفاخر في القصبة أو شرفات فندق المنزه الرائعة تقدم عشاء راقياً مع إطلالات بانورامية خلابة"),
    ("restaurants", "street_food", "Quelle street food goûter absolument ?", "What street food to absolutely taste?", "ما هو طعام الشارع الذي يجب تذوقه بالتأكيد؟",
     "Ne manquez surtout pas le Kalinti (une succulente tarte salée à la farine de pois chiche) et les fameux sandwichs aux brochettes grillées",
     "Do not miss Kalinti (a succulent savory chickpea flour tart) and the famous street sandwiches with grilled meat skewers",
     "لا تفوت الكالينتي (فطيرة مالحة شهية بدقيق الحمص) وسندويشات الشارع الشهيرة مع أسياخ اللحم المشوي"),
    ("restaurants", "prix_moyen", "Quel est le budget pour un repas ?", "What is the budget for a meal?", "ما هي ميزانية الوجبة؟",
     "Comptez 40-70 MAD dans les snacks locaux, 150-250 MAD pour un bon restaurant classique, et plus de 400 MAD pour une table gastronomique",
     "Expect 40-70 MAD in local snacks, 150-250 MAD for a good classic restaurant, and over 400 MAD for a fine dining table",
     "احسب 40-70 درهم في المطاعم المحلية، 150-250 درهم لمطعم كلاسيكي جيد، وأكثر من 400 درهم لمطعم فاخر"),

    # HOTELS (6)
    ("hotels", "hotel_luxe", "Quels sont les meilleurs hôtels 5 étoiles ?", "What are the best 5-star hotels?", "ما هي أفضل الفنادق 5 نجوم؟",
     "Pour le grand luxe, l'historique El Minzah, le très spectaculaire Fairmont Tazi Palace ou le moderne Hilton City Center sont incontournables",
     "For pure luxury, the historic El Minzah, the very spectacular Fairmont Tazi Palace or the modern Hilton City Center are absolute must-stays",
     "للفخامة الكبيرة، فندق المنزه التاريخي، أو قصر التازي فيرمونت المذهل أو هيلتون سيتي سنتر الحديث لا غنى عنها مطلقاً"),
    ("hotels", "riad_medina", "Est-il bien de dormir dans la médina ?", "Is it good to sleep in the medina?", "هل من الجيد النوم في المدينة القديمة؟",
     "Loger dans un somptueux riad traditionnel (comme La Tangerina) est une expérience féerique qui vous plonge littéralement au cœur de l'histoire locale",
     "Staying in a sumptuous traditional riad (like La Tangerina) is a magical experience that literally plunges you into the heart of local history",
     "الإقامة في رياض تقليدي فخم (مثل لا طنجرينا) هي تجربة ساحرة تغمرك حرفياً في قلب التاريخ المحلي"),
    ("hotels", "hotel_budget", "Où loger avec un petit budget ?", "Where to stay on a tight budget?", "أين أقيم بميزانية محدودة؟",
     "Le quartier central du Grand Socco regorge de petites auberges de jeunesse et de pensions économiques offrant un excellent rapport qualité-prix",
     "The central Grand Socco area is full of small youth hostels and budget guesthouses offering an excellent value for money",
     "تزخر منطقة السوق الكبير المركزية بنزل الشباب الصغيرة والبنسيونات الاقتصادية التي تقدم قيمة ممتازة مقابل المال"),
    ("hotels", "hotel_plage", "Quels hôtels sont directement sur la plage ?", "Which hotels are right on the beach?", "ما الفنادق الموجودة مباشرة على الشاطئ؟",
     "Les grands complexes hôteliers prestigieux situés le long de la magnifique baie de Malabata, comme le Mövenpick ou le Barcelo, font face à la mer",
     "The prestigious large hotel complexes located along the beautiful Malabata bay, like the Mövenpick or Barcelo, directly face the sea",
     "المنتجعات الفندقية الكبيرة المرموقة الواقعة على طول خليج ملاباطا الجميل، مثل موفنبيك أو بارسيلو، تواجه البحر مباشرة"),
    ("hotels", "quartier_choix", "Dans quel quartier vaut-il mieux loger ?", "Which neighborhood is best to stay in?", "في أي حي يفضل الإقامة؟",
     "La Médina est de loin idéale pour l'authenticité piétonne, tandis que la Ville Nouvelle est parfaite si vous avez absolument besoin d'un parking",
     "The Medina is by far ideal for pedestrian authenticity, while the New City is perfect if you absolutely need a car parking space",
     "المدينة القديمة مثالية للأصالة والمشاة، بينما المدينة الجديدة مثالية إذا كنت بحاجة ماسة إلى موقف لسيارتك"),
    ("hotels", "reservation", "Faut-il réserver son hôtel à l'avance ?", "Should I book my hotel in advance?", "هل يجب حجز الفندق مسبقاً؟",
     "Il est toujours fortement recommandé de réserver plusieurs mois à l'avance, tout particulièrement en juillet et août lorsque l'affluence est à son maximum absolu",
     "It is always highly recommended to book several months in advance, especially in July and August when tourist crowds are at their absolute peak",
     "يوصى دائماً بشدة بالحجز قبل عدة أشهر، خاصة في شهري يوليو وأغسطس عندما تكون الحشود السياحية في ذروتها المطلقة"),

    # URGENCES (6)
    ("urgences", "numero_police", "Quel est le numéro de la police ?", "What is the police number?", "ما هو رقم الشرطة؟",
     "En cas de problème en ville, le numéro gratuit de la police est le 19. Hors agglomération, contactez rapidement la gendarmerie royale au 177",
     "In case of a problem in town, the toll-free police number is 19. Outside the city limits, quickly contact the royal gendarmerie at 177",
     "في حالة وجود مشكلة في المدينة، رقم الشرطة المجاني هو 19. خارج المنطقة الحضرية، اتصل بسرعة بالدرك الملكي على 177"),
    ("urgences", "numero_pompier", "Quel est le numéro des urgences médicales ?", "What is the medical emergency number?", "ما هو رقم الطوارئ الطبية؟",
     "Pour toute urgence médicale grave ou un incendie, appelez immédiatement la Protection Civile (les pompiers et ambulances) en composant directement le 15",
     "For any serious medical emergency or fire, immediately call the Civil Protection (firemen and emergency ambulances) by dialing 15 directly",
     "لأي طوارئ طبية خطيرة أو حريق، اتصل فوراً بالوقاية المدنية (المطافئ وسيارات الإسعاف) عن طريق الاتصال مباشرة بالرقم 15"),
    ("urgences", "hopital_recommande", "Quel hôpital recommandez-vous ?", "Which hospital do you recommend?", "أي مستشفى تنصح به؟",
     "La grande Clinique Al Amal et l'Hôpital Espagnol Duc de Tovar offrent des services d'urgence fiables 24h/24 ainsi que d'excellents soins médicaux",
     "The large Clinique Al Amal and the Spanish Hospital Duc de Tovar offer reliable 24/7 emergency services as well as excellent medical care",
     "تقدم عيادة الأمل الكبيرة والمستشفى الإسباني دوق دي توفار خدمات طوارئ موثوقة على مدار 24 ساعة بالإضافة إلى رعاية طبية ممتازة"),
    ("urgences", "pharmacie_garde", "Comment trouver une pharmacie ouverte la nuit ?", "How to find an open pharmacy at night?", "كيف أجد صيدلية مفتوحة ليلاً؟",
     "L'indispensable liste des pharmacies de garde est toujours affichée sur la porte de chaque pharmacie. Celles de Pasteur et Rif ferment généralement très tard",
     "The essential list of on-duty pharmacies is always posted on every pharmacy door. Pasteur and Rif pharmacies generally close very late",
     "تُعرض قائمة الصيدليات المناوبة الضرورية دائماً على باب كل صيدلية. غالباً ما تغلق صيدليتي باستور والريف في وقت متأخر جداً"),
    ("urgences", "perte_passeport", "Que faire en cas de perte de passeport ?", "What to do if passport is lost?", "ماذا تفعل في حالة فقدان جواز السفر؟",
     "Faites vite une déclaration de perte officielle au Commissariat Central, puis contactez immédiatement le consulat de votre pays d'origine situé à Tanger",
     "Quickly make an official loss declaration at the Central Police Station, then immediately contact your home country's consulate located in Tangier",
     "قم بسرعة بعمل تصريح رسمي بالضياع في المفوضية المركزية، ثم اتصل فوراً بقنصلية بلدك الأصلي الموجودة في طنجة"),
    ("urgences", "securite", "Tanger est-elle une ville sûre ?", "Is Tangier a safe city?", "هل طنجة مدينة آمنة؟",
     "Tanger est globalement une ville très sûre pour les touristes. Faites simplement attention aux habiles pickpockets dans les lieux extrêmement bondés comme les marchés",
     "Tangier is overall a very safe city for tourists. Just pay attention to skilled pickpockets in extremely crowded places like the bustling markets",
     "طنجة مدينة آمنة جداً بشكل عام للسياح. انتبه فقط للنشالين المهرة في الأماكن المزدحمة للغاية مثل الأسواق الصاخبة"),

    # CULTURE (8)
    ("culture", "langues_parlees", "Quelles langues sont parlées à Tanger ?", "What languages are spoken in Tangier?", "ما هي اللغات المتحدث بها في طنجة؟",
     "La langue locale principale est la darija. L'espagnol et le français sont couramment maîtrisés par presque tous les commerçants, facilitant grandement les échanges",
     "The main local language is darija. Spanish and French are fluently mastered by almost all shopkeepers, greatly facilitating daily interactions",
     "اللغة المحلية الرئيسية هي الدارجة. يتقن معظم التجار التحدث بالإسبانية والفرنسية بطلاقة، مما يسهل التفاعلات اليومية بشكل كبير"),
    ("culture", "tenue_vestimentaire", "Comment s'habiller à Tanger ?", "How to dress in Tangier?", "كيف ترتدي ملابسك في طنجة؟",
     "Une tenue décontractée est parfaitement acceptée, mais il est toujours très respectueux de bien couvrir vos épaules et genoux, particulièrement dans les quartiers historiques",
     "Casual attire is perfectly accepted, but it is always very respectful to properly cover your shoulders and knees, particularly in historic neighborhoods",
     "اللباس غير الرسمي مقبول تماماً، لكن من الاحترام دائماً تغطية الكتفين والركبتين بشكل مناسب، خاصة في الأحياء التاريخية القديمة"),
    ("culture", "pourboire_pratique", "Doit-on laisser un pourboire ?", "Should we leave a tip?", "هل يجب ترك بقشيش؟",
     "Le pourboire n'est jamais obligatoire mais il est coutumier et très apprécié. On laisse généralement 5 à 10% de l'addition dans les bons restaurants",
     "Tipping is never mandatory but it is customary and highly appreciated. People generally leave 5 to 10% of the bill in good restaurants",
     "البقشيش ليس إلزامياً أبداً ولكنه معتاد ومقدر جداً. يترك الناس عموماً 5 إلى 10٪ من إجمالي الفاتورة في المطاعم الجيدة"),
    ("culture", "festivals", "Quels sont les festivals à Tanger ?", "What are the festivals in Tangier?", "ما هي المهرجانات في طنجة؟",
     "La ville vibre intensément au rythme du très célèbre festival Tanjazz en septembre et de l'incontournable et prestigieux Festival National du Film marocain",
     "The city vibrates intensely to the rhythm of the very famous Tanjazz festival in September and the unmissable prestigious National Moroccan Film Festival",
     "تنبض المدينة بقوة على إيقاع مهرجان طنجاز الشهير جداً في سبتمبر والمهرجان الوطني للفيلم المغربي المرموق الذي لا يفوت"),
    ("culture", "marchandage", "Faut-il marchander dans les souks ?", "Should you haggle in the souks?", "هل يجب المساومة في الأسواق؟",
     "Oui, le marchandage est une vraie et ancienne tradition locale. N'hésitez pas à proposer calmement la moitié du prix et à négocier avec un grand sourire",
     "Yes, haggling is a true and ancient local tradition. Do not hesitate to calmly offer half the price and negotiate with a big smile",
     "نعم، المساومة تقليد محلي حقيقي وقديم. لا تتردد في اقتراح نصف السعر بهدوء والتفاوض بابتسامة عريضة طوال الوقت"),
    ("culture", "artisanat", "Quel artisanat acheter à Tanger ?", "What crafts to buy in Tangier?", "ما هي الحرف اليدوية التي يمكن شراؤها في طنجة؟",
     "Tanger est mondialement réputée pour ses beaux articles en cuir véritable, ses céramiques richement colorées du Rif et les typiques chapeaux de paille à pompons",
     "Tangier is world-renowned for its beautiful genuine leather goods, its richly colored Rif ceramics and typical pom-pom straw hats",
     "تشتهر طنجة عالمياً بالسلع الجلدية الأصلية الجميلة، وخزف الريف الملون الغني وقبعات القش التقليدية المزينة بكرات الصوف"),
    ("culture", "vendredi_sacre", "Que se passe-t-il le vendredi ?", "What happens on Friday?", "ماذا يحدث يوم الجمعة؟",
     "Le vendredi est le jour sacré de la semaine. Beaucoup de boutiques ferment systématiquement à la mi-journée pour la prière, et c'est le jour traditionnel du couscous",
     "Friday is the sacred day of the week. Many shops systematically close at midday for prayer, and it is the traditional day for family couscous",
     "الجمعة هو اليوم المقدس في الأسبوع. تغلق العديد من المتاجر بشكل منهجي في منتصف النهار للصلاة، وهو اليوم التقليدي لطبق الكسكس العائلي"),
    ("culture", "photos_locaux", "Peut-on photographier les habitants ?", "Can we photograph the locals?", "هل يمكن تصوير السكان المحليين؟",
     "Demandez systématiquement l'autorisation explicite avant de photographier quelqu'un. Certaines personnes, plus particulièrement les anciens dans la médina, n'apprécient pas du tout d'être photographiées",
     "Always ask for explicit permission before photographing anyone. Some people, more particularly the elders in the medina, do not appreciate being photographed at all",
     "اطلب دائماً الإذن الصريح قبل تصوير أي شخص. بعض الناس، وخاصة كبار السن في المدينة القديمة، لا يقدرون على الإطلاق التقاط صور لهم"),

    # METEO (4)
    ("meteo", "meilleure_periode", "Quelle est la meilleure période pour venir ?", "What is the best time to come?", "ما هو أفضل وقت للمجيء؟",
     "Le printemps radieux et l'automne offrent incontestablement le meilleur climat. Les températures y sont idéales pour explorer confortablement sans souffrir de la lourde chaleur estivale",
     "Radiant spring and autumn unquestionably offer the best climate. Temperatures are ideal there to explore comfortably without suffering from the heavy summer heat",
     "يوفر الربيع المشرق والخريف بلا شك أفضل مناخ. درجات الحرارة مثالية هناك للاستكشاف براحة تامة دون المعاناة من حرارة الصيف الثقيلة"),
    ("meteo", "climat_hiver", "Fait-il très froid en hiver ?", "Is it very cold in winter?", "هل الجو بارد جداً في الشتاء؟",
     "Les hivers marocains sont assez doux (entre 10 et 15 degrés) mais l'importante humidité ambiante et les vents marins peuvent considérablement accentuer la sensation de froid",
     "Moroccan winters are quite mild (between 10 and 15 degrees) but the high ambient humidity and sea winds can considerably accentuate the cold sensation",
     "فصول الشتاء المغربية معتدلة (بين 10 و 15 درجة) لكن الرطوبة العالية المحيطة والرياح البحرية يمكن أن تزيد بشكل كبير من الشعور بالبرد"),
    ("meteo", "vent_chergui", "Qu'est-ce que le vent Chergui ?", "What is the Chergui wind?", "ما هي رياح الشرقي؟",
     "Le redoutable Chergui est un vent d'est très chaud et sec qui souffle occasionnellement l'été, augmentant alors considérablement les températures ressenties dans toute la région",
     "The formidable Chergui is a very hot and dry east wind that occasionally blows in summer, then considerably increasing the perceived temperatures throughout the region",
     "الشرقي المخيف هي رياح شرقية حارة وجافة جداً تهب أحياناً في الصيف، مما يزيد بشكل كبير من درجات الحرارة المحسوسة في جميع أنحاء المنطقة"),
    ("meteo", "baignade_mer", "Quand l'eau est-elle bonne pour la baignade ?", "When is the water good for swimming?", "متى يكون الماء مناسباً للسباحة؟",
     "La période balnéaire idéale s'étend de juin à fin septembre. Sachez que l'eau tonique de l'océan Atlantique y reste toujours fraîche, dépassant rarement les 22 degrés",
     "The ideal beach period runs from June to late September. Note that the tonic water of the Atlantic Ocean always stays fresh, rarely exceeding 22 degrees",
     "تمتد فترة الشاطئ المثالية من يونيو إلى أواخر سبتمبر. لاحظ أن المياه المنعشة للمحيط الأطلسي تظل باردة دائماً، ونادراً ما تتجاوز 22 درجة"),

    # MONNAIE (4)
    ("monnaie", "devise_locale", "Quelle monnaie est utilisée ?", "What currency is used?", "ما هي العملة المستخدمة؟",
     "La monnaie officielle nationale est le Dirham Marocain (MAD). Pour vous donner une idée précise et simple, 1 Euro vaut généralement de manière stable autour de 10,8 MAD",
     "The official national currency is the Moroccan Dirham (MAD). To give you a precise and simple idea, 1 Euro is generally stably worth around 10.8 MAD",
     "العملة الوطنية الرسمية هي الدرهم المغربي. لإعطائك فكرة دقيقة وبسيطة، 1 يورو يعادل عادة بشكل مستقر حوالي 10.8 درهم"),
    ("monnaie", "bureaux_change", "Où faut-il changer son argent ?", "Where to exchange money?", "أين يجب صرف الأموال؟",
     "Privilégiez toujours fortement les bureaux de change officiels situés sur le Boulevard Pasteur en centre-ville, leurs taux de conversion sont indéniablement bien plus avantageux qu'à l'aéroport",
     "Always strongly prefer the official exchange offices located on Boulevard Pasteur in the city center, their conversion rates are undeniably much better than at the airport",
     "فضل دائماً وبقوة مكاتب الصرف الرسمية الواقعة في شارع باستور بوسط المدينة، فإن أسعار التحويل الخاصة بها أفضل بكثير بلا شك من المطار"),
    ("monnaie", "paiement_carte", "Peut-on payer partout par carte bancaire ?", "Can we pay everywhere by credit card?", "هل يمكننا الدفع في كل مكان بالبطاقة المصرفية؟",
     "Les cartes internationales sont acceptées dans les grands établissements modernes, mais il est absolument vital de toujours garder de l'espèce sur soi pour les taxis et les petits commerces",
     "International cards are accepted in large modern establishments, but it is absolutely vital to always keep some cash on you for local taxis and small shops",
     "تُقبل البطاقات الدولية في المؤسسات الحديثة الكبيرة، ولكن من الضروري للغاية الاحتفاظ دائماً ببعض النقود معك لسيارات الأجرة المحلية والمتاجر الصغيرة"),
    ("monnaie", "distributeurs_atm", "Trouve-t-on facilement des distributeurs ?", "Are ATMs easily found?", "هل يسهل العثور على أجهزة الصراف الآلي؟",
     "Les distributeurs automatiques de billets (GAB) sont très répandus et accessibles dans toute la ville. Attention tout de même, votre propre banque pourrait appliquer des frais de retrait internationaux",
     "Automated Teller Machines (ATMs) are very widespread and accessible throughout the city. Be careful though, your own bank might apply some international withdrawal fees",
     "تنتشر أجهزة الصراف الآلي بشكل كبير ويمكن الوصول إليها في جميع أنحاء المدينة. كن حذراً رغم ذلك، فقد يطبق البنك الخاص بك بعض رسوم السحب الدولية")
]

faqs = []
for i, item in enumerate(facts):
    cat, scat, qf, qe, qa, sf, se, sa = item
    
    t_fr = random.choice(templates_fr)
    t_en = random.choice(templates_en)
    t_ar = random.choice(templates_ar)
    
    rf = t_fr.format(spec=sf)
    re = t_en.format(spec=se)
    ra = t_ar.format(spec=sa)
    
    faqs.append({
        "id": f"faq_{i+1:03d}",
        "categorie": cat,
        "sous_categorie": scat,
        "intention": f"{cat}_{scat}",
        "priorite": 1 if cat in ["urgences", "transport"] else 2,
        "question_fr": qf,
        "question_en": qe,
        "question_ar": qa,
        "reponse_fr": rf,
        "reponse_en": re,
        "reponse_ar": ra,
        "tags": [cat, scat, "pratique", "tanger"],
        "entites_mentionnees": [scat.replace('_', ' ').title(), "Tanger"],
        "lien_utile": None,
        "telephone_utile": None,
        "source_donnee": "Office Tourisme Tanger + Données Expertes"
    })

with open(r'c:\Users\HP\Documents\projet touristique\dataset\faq_chatbot.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)

print(f"Total FAQs générées : {len(faqs)}")
